/* GENERATED by tools/stamp.py — do not edit.
   `modified` is the newest mtime across src/, styles/ and the generated
   tables, so the title screen reports when the GAME changed. */
const BUILD = { version: "v0.40", modified: "28 Aug 2026  00:07" };
