/* =====================================================================
   NEURO-METRO: AVUI — DATA TABLES
   GENERATED by tools/build_data.py from the config spreadsheet.
   Edit the spreadsheet, export the sheets as CSV, re-run the script.
   Hand edits here are fine for a quick test but will be overwritten.
   ===================================================================== */

const SCHEMA = {
  bool: ["hits_layer", "enabled"],
  list: ["layers", "pool", "loadouts", "emotions", "lines", "stations", "spawn",
        "spawn_lines", "day", "weather", "keys", "drops", "reward"]
};

const DATA = {

/* --- emotions ---
   one row per emotion. `token` maps to the CSS palette variable.  */
emotions: `id,name,token,hex,bg_hex,short,icon,sfx,description,enabled,notes
ANGER,Anger,anger,#e53859,#2a0810,ANG,BOLT,hit_anger,"Hot, direct, aggressive.",1,
SURPRISE,Surprise,surprise,#724082,#170a1b,SUR,BURST,hit_surprise,"Sudden, disruptive, disorienting.",1,
DISGUST,Disgust,disgust,#56a36a,#0c1f13,DIS,ROT,hit_disgust,"Rejecting, corrosive, contemptuous.",1,
JOY,Joy,joy,#fcc336,#2a1f06,JOY,SPARK,hit_joy,"Bright, volatile, energising.",1,
SADNESS,Sadness,sadness,#3d66c1,#0a1229,SAD,DROP,hit_sadness,"Heavy, draining, persistent.",1,
FEAR,Fear,fear,#929fa5,#1a1e20,FEA,EYE,hit_fear,"Cold, freezing, evasive.",1,`,

/* --- abilities ---
   kind DAMAGE|SHIELD · power = damage or shield charges · blank emotion = typeless
   (never matches a layer) · hits_layer = whether a hit rotates the target's queue.  */
abilities: `id,name,emotion,cost,kind,power,charge,hits_layer,icon,target,reach,self_ms,self_ec,ec_push_target,ec_drain_target,heal,shield_gain,pierce_shield,ignore_layer,repeat,cooldown,uses,blurb,action,emotions,crit_chance,status_apply,status_chance,status_duration,combo_tag,requires_prev_tag,synergy_group,wild_target,rarity,unlock,enabled,notes
ATK_ANGER,Heated Punch,ANGER,20,DAMAGE,35,0,1,BOLT,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,3,Attack. Cracks the outermost {LAYER}.,0,,,,0,0,,,,LOWEST_MS,COMMON,,1,
ATK_SADNESS,Cold Shoulder,SADNESS,20,DAMAGE,35,0,1,DROP,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,3,Attack. Cracks the outermost {LAYER}.,0,,,,0,0,,,,LOWEST_MS,COMMON,,1,
ATK_JOY,Manic Grin,JOY,20,DAMAGE,35,0,1,SPARK,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,3,Attack. Cracks the outermost {LAYER}.,0,,,,0,0,,,,LOWEST_MS,COMMON,,1,
DEFEND,Block,,10,SHIELD,1,0,0,SHIELD,SELF,SINGLE,0,0,0,0,0,1,0,0,1,1,3,Defence. Blocks the next hit outright.,1,,,,0,0,,,,SELF,COMMON,,1,
HVY_ANGER,Rage,ANGER,45,DAMAGE,90,2,1,BOLT,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,2,"Attack. *Charges* first, then hits for triple.",0,,,,0,0,,,,LOWEST_MS,COMMON,,1,
HVY_SADNESS,Grief,SADNESS,45,DAMAGE,90,2,1,DROP,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,2,"Attack. *Charges* first, then hits for triple.",0,,,,0,0,,,,LOWEST_MS,COMMON,,1,
HVY_JOY,Mania,JOY,60,DAMAGE,130,3,1,SPARK,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,2,"Attack. The hardest hit there is, after a long *charge*.",0,,,,0,0,,,,LOWEST_MS,COMMON,,1,
RECHARGE,Recharge,,0,CHARGE,20,0,0,CHARGE,SELF,SINGLE,5,0,0,0,0,0,0,0,1,1,3,Buff. Trades your own {MS} for {EC}.,1,,,,0,0,,,,SELF,COMMON,,1,Gains 20 EC and costs 5 of your own MS — which also lowers your ceiling.
GEN_DISGUST,Bile,DISGUST,15,ADDLAYER,1,0,0,ROT,SELF,SINGLE,0,0,0,0,0,0,0,0,1,1,2,Defence. Grows a {LAYER} that *never regrows* once broken.,0,,,,0,0,,,,SELF,COMMON,,1,Grows one extra Disgust layer. Grown layers are TEMPORARY: once broken they never regrow.
GEN_ANGER,Bristle,ANGER,15,ADDLAYER,1,0,0,ROT,SELF,SINGLE,0,0,0,0,0,0,0,0,1,1,2,Defence. Grows a {LAYER} that *never regrows* once broken.,0,,,,0,0,,,,SELF,COMMON,,1,Grows one extra Anger layer. Grown layers are TEMPORARY: once broken they never regrow.
GEN_JOY,Good Vibes,JOY,15,ADDLAYER,1,0,0,SPARK,SELF,SINGLE,0,0,0,0,0,0,0,0,1,1,2,Defence. Grows a {LAYER} that *never regrows* once broken.,0,,,,0,0,,,,SELF,COMMON,,1,Grows one extra Joy layer. Grown layers are TEMPORARY: once broken they never regrow.
ROT,Fester,DISGUST,25,DEBUFF,0,0,0,ROT,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,2,Debuff. Target cannot regrow *2* {LAYERS} for *2 turns*.,0,,,NO_REGEN,0,2,,,,LOWEST_MS,COMMON,,1,For 2 turns the target cannot regrow 2 of its broken layers.
INFLICT_SAD,Self-Harm,SADNESS,30,DEBUFF,0,0,0,DROP,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,2,Status. Target attacks *itself* each round for *2 turns*.,0,,,SAD,0,2,,,,LOWEST_MS,COMMON,,1,"Each round end the target turns one of its own attacks on itself. NOTE: distinct from SELF_HARM, which is the Overload-forced station."
BLIND,Blinded by Hate,ANGER,30,DEBUFF,0,0,0,EYE,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,2,Debuff. Target *misses half* its attacks for *2 turns*.,0,,,BLINDED,0,2,,,,LOWEST_MS,COMMON,,1,ENEMY ability. The target misses half its attacks for 2 turns.
ATK_SURPRISE,Sucker Punch,SURPRISE,20,DAMAGE,35,0,1,BURST,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,3,Attack. Cracks the outermost {LAYER}.,0,,,,0,0,,,,LOWEST_MS,COMMON,,1,
HVY_SURPRISE,Whiplash,SURPRISE,45,DAMAGE,90,2,1,BURST,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,2,"Attack. *Charges* first, then hits for triple.",0,,,,0,0,,,,LOWEST_MS,COMMON,,1,
MID_SURPRISE,Double Take,SURPRISE,30,DAMAGE,60,1,1,BURST,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,2,"Attack. *Charges* once, then hits hard.",0,,,,0,0,,,,LOWEST_MS,COMMON,,1,"Between ATK_SURPRISE and HVY_SURPRISE in every respect: one charging station rather than none or two, and power to match. The Set of Jolt is built around it."
STARTLE,Out of Nowhere,SURPRISE,25,DEBUFF,0,0,0,BURST,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,2,Debuff. Target *misses a third* of its attacks for *2 turns*.,0,,,RATTLED,0,2,,,,LOWEST_MS,COMMON,,1,"Surprise's debuff. Softer than BLIND and cheaper, because Surprise pays for it with a weaker basic economy rather than with a bigger bill."
DRUG_HIT,Drug Hit,SURPRISE,20,DAMAGE,35,0,1,BURST,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,3,Attack. Cracks the outermost {LAYER} and leaves them *Dizzy* for a turn.,0,,,DIZZY,0,1,,,,LOWEST_MS,COMMON,,1,"Costed as a BASIC - exactly ATK_SURPRISE's cost and power - because Dizzy lasts one turn and is a coin flip rather than a lock. The Set of Rush leaves it, and it is the only thing in that set, so it has to be worth carrying on its own."
SELF_HARM,Self Harm,,0,SELFHARM,25,0,0,WARN,SELF,SINGLE,0,0,0,0,0,0,0,0,1,0,0,Status. Forced by {OVERLOAD}; costs you {MS}.,0,,,,0,0,,,,SELF,OVERLOAD,,1,OVERLOAD ONLY. Forced into your line when Charge passes your ceiling. Cannot be moved or removed.
FEED,Feed,,0,FEED,30,0,0,DROP,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,0,0,Status. Forced by {OVERLOAD}; *heals* your opponent.,0,,,,0,0,,,,AS_WRITTEN,OVERLOAD,,1,OVERLOAD ONLY. Heals your opponent. Cannot be moved or removed.`,

/* --- matchups ---
   attack emotion x layer emotion. '*' is a wildcard, 'NONE' means the target has
   no layers. Highest priority wins, so a specific pair always beats a wildcard.
   Adding a synergy is adding a row.  */
matchups: `attack_emotion,layer_emotion,priority,dmg_mult,ec_mult,label,tag_class,sound,rotates_layer,self_ec,status_apply,enabled,notes
*,*,0,1,0,OFF TYPE,off,hit,,0,,1,Fallback. Every pair you do not name lands here.
*,NONE,5,2,0,EXPOSED!,dmg,hit,,0,,1,"No layers left: double damage, no charge."
ANGER,ANGER,10,0.5,1,ABSORBED!,absorb,absorb,,0,,1,Same emotion: the layer drinks it.
SURPRISE,SURPRISE,10,0.5,1,ABSORBED!,absorb,absorb,,0,,1,Same emotion: the layer drinks it.
DISGUST,DISGUST,10,0.5,1,ABSORBED!,absorb,absorb,,0,,1,Same emotion: the layer drinks it.
JOY,JOY,10,0.5,1,ABSORBED!,absorb,absorb,,0,,1,Same emotion: the layer drinks it.
SADNESS,SADNESS,10,0.5,1,ABSORBED!,absorb,absorb,,0,,1,Same emotion: the layer drinks it.
FEAR,FEAR,10,0.5,1,ABSORBED!,absorb,absorb,,0,,1,Same emotion: the layer drinks it.`,

/* --- units ---
   layers are outermost-first and rotate as they take hits. pool = usable abilities.
   tier is WEAK|REGULAR|STRONG and decides the SILHOUETTE, not the stats. spawn_lines is
   line:weight, `*` for every line - where the map may produce this enemy.  */
units: `id,name,emotion,tier,max_ms,start_ec_pct,layers,pool,line_dir,line_cap,max_bonus_slots,loadouts,spawn_lines,drops,persona,role,scale,bg_bright,fx,theme_opening,theme_loop,theme2_loop,ai_profile,init,start_shield,max_layers_override,tags,enabled,notes
player,You,,,400,0.5,JOY|SADNESS,ATK_ANGER|ATK_SADNESS|ATK_JOY|DEFEND|RECHARGE|HVY_ANGER|HVY_SADNESS|HVY_JOY|GEN_DISGUST|GEN_ANGER|ROT|INFLICT_SAD,1,3,6,LO_ANGER|LO_SADNESS|LO_JOY,,,,,,,,,,,,10,0,,PLAYER,1,
enemy,The Commuter,ANGER,REGULAR,250,0.4,ANGER|ANGER|SADNESS,ATK_ANGER|ATK_SADNESS|ATK_JOY|DEFEND|RECHARGE|HVY_ANGER|HVY_SADNESS|HVY_JOY|BLIND,-1,3,6,,L1:1.2|*:0.75,CRYSTAL:2:0.75|SEGMENT:3:0.55|ORB:1:0.40,,,,,,,,,GREEDY_MAX_DAMAGE,8,0,,ENEMY,1,"AI reads the matchups sheet, so retuning it retunes the AI. \`drops\` is what beating this one may leave. The \`*\` in spawn_lines is what stops L3, L4 and L6 being empty of enemies until they have units of their own — the Commuter rides every line, which is the joke and also the fallback."
enemy_anger_strong,The Enforcer,ANGER,STRONG,330,0.5,ANGER|ANGER|ANGER|SADNESS,ATK_ANGER|HVY_ANGER|GEN_ANGER|BLIND|ATK_SADNESS|DEFEND|RECHARGE,-1,3,6,,L1:0.14,CRYSTAL:3:0.85|SEGMENT:4:0.70|ORB:1:0.55,,,,,,,,,GREEDY_MAX_DAMAGE,8,0,,ENEMY,1,"Anger, turned up: one more layer than the Commuter and a third more stamina, and its pool is nearly all Anger, so an Anger-layered player is drinking most of it while anyone else is not."
enemy_surprise,The Interruption,SURPRISE,REGULAR,240,0.4,SURPRISE|SURPRISE|ANGER,ATK_SURPRISE|HVY_SURPRISE|STARTLE|ATK_ANGER|DEFEND|RECHARGE,-1,3,6,,L2:1.2,CRYSTAL:2:0.75|SEGMENT:3:0.55|ORB:1:0.40,,,,,,,,,GREEDY_MAX_DAMAGE,8,0,,ENEMY,1,L2's own. Slightly under the Commuter on stamina because STARTLE is worth more than it costs when it lands.
enemy_surprise_strong,The Reversal,SURPRISE,STRONG,320,0.5,SURPRISE|SURPRISE|SURPRISE|JOY,ATK_SURPRISE|HVY_SURPRISE|STARTLE|GEN_ANGER|ATK_JOY|DEFEND|RECHARGE,-1,3,6,,L2:0.12,CRYSTAL:3:0.85|SEGMENT:4:0.70|ORB:1:0.55,,,,,,,,,GREEDY_MAX_DAMAGE,8,0,,ENEMY,1,"Three Surprise layers deep. GEN_ANGER is in the pool so it can grow a layer that does NOT absorb Surprise, which is the counter to a player who came dressed for it."
enemy_sadness_weak,The Straggler,SADNESS,WEAK,150,0.3,SADNESS|SADNESS,ATK_SADNESS|INFLICT_SAD|DEFEND|RECHARGE,-1,2,4,,L2:0.6|L5:0.7,CRYSTAL:1:0.45|SEGMENT:2:0.40,,,,,,,,,GREEDY_MAX_DAMAGE,8,0,,ENEMY,1,"No heavy in the pool, on purpose: a WEAK enemy chips. Two slots, two layers, and INFLICT_SAD is the one thing it can do that you will remember. RARE EVEN AT HOME — the sheet says L5 at 0.15, not 1.0, because it was asked for as an uncommon sight on both its lines. Raise the L5 cell to make it Line 5's regular."
enemy_joy_weak,The Reveller,JOY,WEAK,150,0.3,JOY|JOY,ATK_JOY|GEN_JOY|DEFEND|RECHARGE,-1,2,4,,L2:0.6,CRYSTAL:1:0.45|SEGMENT:2:0.40,,,,,,,,,GREEDY_MAX_DAMAGE,8,0,,ENEMY,1,"L2 ONLY, and rarely — it is not on L4, its own colour's line, because that is how it was asked for. Reads as Line 2 being where the wrong people end up. Add \`|L4:1.0\` to give Joy its own regular."
boss_fondo,The Terminus,ANGER,STRONG,430,0.55,ANGER|ANGER|ANGER|ANGER,ATK_ANGER|HVY_ANGER|GEN_ANGER|BLIND|DEFEND|RECHARGE,-1,4,6,,,CRYSTAL:4:1.0|SEGMENT:4:0.80|ORB:2:0.70,The Terminus,,,,,,,,GREEDY_MAX_DAMAGE,8,0,,ENEMY,1,"The end of Line 1, and the armor it leaves is four layers of Anger - so the fight that grants it is four layers of Anger. Pure type on purpose: an Anger-layered player drinks half of this, which is exactly the trade the reward is offering."
boss_sant_antoni,The Comedown,SURPRISE,STRONG,400,0.55,SURPRISE|SURPRISE|JOY|SURPRISE,ATK_SURPRISE|HVY_SURPRISE|MID_SURPRISE|STARTLE|GEN_JOY|DEFEND|RECHARGE,-1,4,6,,,CRYSTAL:4:1.0|SEGMENT:4:0.80|ORB:2:0.70,The Comedown,,,,,,,,GREEDY_MAX_DAMAGE,8,0,,ENEMY,1,Leaves the Set of Rush. Its own pool is what the set is not: volume. The reward for beating a thing that swings six times is one ability that swings once and staggers.
boss_line_manager,The Line Manager,JOY,STRONG,520,0.6,JOY|JOY|JOY|SURPRISE|JOY,ATK_JOY|HVY_JOY|GEN_JOY|ATK_SURPRISE|STARTLE|DEFEND|RECHARGE,-1,4,6,,,CRYSTAL:5:1.0|SEGMENT:5:0.90|ORB:2:0.80,The Line Manager,LINE_MANAGER,1.5,3,PAPARAZZI,,audio/line-manager.m4a,audio/line-manager-phase2.m4a,GREEDY_MAX_DAMAGE,8,0,,ENEMY,1,"THE KEY TO LINE 4 IS BEHIND HER. Five layers, nearly all Joy, because she is not defending a position - she is defending a mood, and every hit that is not Joy is someone ruining it. \`bg_bright\` triples the backdrop tint so her fight is lit like a rooftop rather than a tunnel, \`fx\` fires the camera flashes, and the two theme columns swap the music out for hers alone."`,

/* --- dialogue ---
   what each enemy says. state: INTRO | WINNING | LOSING | DEFEAT. A battle picks one
   persona at random from the rows matching the enemy's emotion.  */
dialogue: `emotion,persona,state,line,tier,enabled,notes
ANGER,The Evicted,INTRO,Thirty years in this flat and they sell it to a fund! I'LL BURN IT DOWN WITH YOU IN IT!,,1,
ANGER,The Evicted,WINNING,Choke on the ashes! CHOKE ON THEM!,,1,
ANGER,The Evicted,LOSING,No... my things... my life...,,1,
ANGER,The Evicted,DEFEAT,Just let me... lock the door... one last time.,,1,
ANGER,The Exploited,INTRO,Fourteen hours biking in the rain for three euros! I'LL BREAK YOUR FUCKING LEGS!,,1,
ANGER,The Exploited,WINNING,Take your luxury takeout and choke on it!,,1,
ANGER,The Exploited,LOSING,My bike... I can't afford to fix my bike...,,1,
ANGER,The Exploited,DEFEAT,The app... it says I'm deactivated...,,1,
ANGER,The Betrayed,INTRO,You think a text message makes up for six months of lies?! I'LL TEAR YOUR THROAT OUT!,,1,
ANGER,The Betrayed,WINNING,Look at me! Look at me when I'm screaming at you!,,1,
ANGER,The Betrayed,LOSING,Stop deflecting... stop making me the crazy one!,,1,
ANGER,The Betrayed,DEFEAT,I just... wanted the truth.,,1,
ANGER,The Vandal,INTRO,This isn't your playground! Get out of my neighborhood before I smash your skull!,,1,
ANGER,The Vandal,WINNING,Go back to your perfect little life!,,1,
ANGER,The Vandal,LOSING,There are too many of you...,,1,
ANGER,The Vandal,DEFEAT,We're being erased...,,1,
ANGER,The Denied,INTRO,Three years waiting for papers and you stamp DENIED?! I'LL KILL EVERYONE HERE!,,1,
ANGER,The Denied,WINNING,Stamp this! STAMP THIS IN BLOOD!,,1,
ANGER,The Denied,LOSING,"Please, you don't understand what they'll do to me...",,1,
ANGER,The Denied,DEFEAT,I don't exist anymore...,,1,
DISGUST,The Aristocrat,INTRO,"Look at you, sweating on the metro. Did you even shower before touching my city?",,1,
DISGUST,The Aristocrat,WINNING,Filth always sinks to the bottom. Stay there.,,1,
DISGUST,The Aristocrat,LOSING,Don't touch me with those calloused hands!,,1,
DISGUST,The Aristocrat,DEFEAT,Your smell... it won't wash off...,,1,
DISGUST,The Apathetic,INTRO,Another addict blocking the ATM. Can't you just die somewhere out of sight?,,1,
DISGUST,The Apathetic,WINNING,Scrape yourself off my shoes.,,1,
DISGUST,The Apathetic,LOSING,Don't bleed on my designer coat!,,1,
DISGUST,The Apathetic,DEFEAT,I am... better than this...,,1,
DISGUST,The Xenophobe,INTRO,"You come here, take our space, speak your garbage language. You make me sick.",,1,
DISGUST,The Xenophobe,WINNING,Clean it up. That's all you're good for.,,1,
DISGUST,The Xenophobe,LOSING,How dare you speak back to me?!,,1,
DISGUST,The Xenophobe,DEFEAT,This isn't... your home...,,1,
DISGUST,The Purist,INTRO,"Plastic faces, fake lips, empty heads. You're a walking infection in this club.",,1,
DISGUST,The Purist,WINNING,Choke on your vanity.,,1,
DISGUST,The Purist,LOSING,Get your cheap perfume away from me.,,1,
DISGUST,The Purist,DEFEAT,It's all so... hollow...,,1,
DISGUST,The Mirror,INTRO,"I see the track marks under your sleeves. You're rotting from the inside, just like me.",,1,
DISGUST,The Mirror,WINNING,We belong in the gutter. Accept it.,,1,
DISGUST,The Mirror,LOSING,Don't look at me with pity!,,1,
DISGUST,The Mirror,DEFEAT,Just... one more hit to make it stop...,,1,
SADNESS,The Left Behind,INTRO,No. Dad didn't leave. Dad loves me... Loved me?,,1,
SADNESS,The Left Behind,WINNING,I'll make you stay! Nobody leaves me again!,,1,
SADNESS,The Left Behind,LOSING,Did I do something wrong?,,1,
SADNESS,The Left Behind,DEFEAT,I'll be good... I promise I'll be good...,,1,
SADNESS,The Isolated,INTRO,The hospital called. Nobody came to claim his things. Am I next?,,1,
SADNESS,The Isolated,WINNING,If you stay down... it hurts less. I promise.,,1,
SADNESS,The Isolated,LOSING,Why does everyone walk away?,,1,
SADNESS,The Isolated,DEFEAT,Finally... it's quiet.,,1,
SADNESS,The Erased,INTRO,My grandfather built this bar. Now it's a fucking brunch spot... I have nothing.,,1,
SADNESS,The Erased,WINNING,Drink the bitterness. It's all we have left.,,1,
SADNESS,The Erased,LOSING,They're painting over the mural...,,1,
SADNESS,The Erased,DEFEAT,I don't recognize my own street.,,1,
SADNESS,The Grieving,INTRO,The sea was supposed to be calm... they promised it was safe to cross...,,1,
SADNESS,The Grieving,WINNING,Drown with me! Drown with my memories!,,1,
SADNESS,The Grieving,LOSING,I can't hold on to the raft...,,1,
SADNESS,The Grieving,DEFEAT,The water is so cold...,,1,
SADNESS,The Broken Dream,INTRO,Ten years playing in the metro... nobody even looks up anymore.,,1,
SADNESS,The Broken Dream,WINNING,LISTEN TO ME! FOR ONCE IN YOUR LIFE!,,1,
SADNESS,The Broken Dream,LOSING,My strings are snapping...,,1,
SADNESS,The Broken Dream,DEFEAT,Silence... just like always.,,1,
FEAR,The Hunted,INTRO,"Shhhh shhhhhhhhh! Those transphobes behind the corner, they'll notice us, move back slowly... oh no OH NO",,1,
FEAR,The Hunted,WINNING,STAY BACK! I HAVE A KNIFE!,,1,
FEAR,The Hunted,LOSING,"Please, I just want to walk home...",,1,
FEAR,The Hunted,DEFEAT,Not again... please not again...,,1,
FEAR,The Paranoid,INTRO,The cameras on the streetlights—they track our heartbeats. Don't let them see you panic!,,1,
FEAR,The Paranoid,WINNING,I'll blind them! I'LL BLIND THE WHOLE CITY!,,1,
FEAR,The Paranoid,LOSING,They're zooming in... they know my name...,,1,
FEAR,The Paranoid,DEFEAT,Erase my... search history...,,1,
FEAR,The Debt-Ridden,INTRO,"I have the money, I swear! Just give me till Friday!",,1,
FEAR,The Debt-Ridden,WINNING,I'll take yours! I'll pay them with your blood!,,1,
FEAR,The Debt-Ridden,LOSING,They're going to break my hands...,,1,
FEAR,The Debt-Ridden,DEFEAT,Tell my mother... I'm sorry...,,1,
FEAR,The Trapped,INTRO,He said he wouldn't hit me again if I just stayed quiet...,,1,
FEAR,The Trapped,WINNING,Don't make him angry! Just do what he says!,,1,
FEAR,The Trapped,LOSING,He's coming up the stairs... I can hear his keys...,,1,
FEAR,The Trapped,DEFEAT,It was always going to end like this...,,1,
FEAR,The Night-Walker,INTRO,Footsteps. Stop. Footsteps. Why are they matching my pace?,,1,
FEAR,The Night-Walker,WINNING,I'll run! You can't catch me in the dark!,,1,
FEAR,The Night-Walker,LOSING,The streetlights are all broken here...,,1,
FEAR,The Night-Walker,DEFEAT,Nobody can hear me scream...,,1,
JOY,The Delusional,INTRO,Life is MINE and this street is MY world to strut by and BLIND YOU WITH MY LIGHT,,1,
JOY,The Delusional,WINNING,Bask in my glory! I am untouched by sorrow!,,1,
JOY,The Delusional,LOSING,Wait... why is everyone looking at me like that?,,1,
JOY,The Delusional,DEFEAT,The spotlight... it's fading...,,1,
JOY,The Substance Abuser,INTRO,"Another pill, another party! The sun never sets in Raval if your eyes are wide enough!",,1,
JOY,The Substance Abuser,WINNING,DANCE WITH ME! WHY AREN'T YOU DANCING?!,,1,
JOY,The Substance Abuser,LOSING,"No, no, the comedown... I can't feel my teeth...",,1,
JOY,The Substance Abuser,DEFEAT,It's so dark... where did the music go?,,1,
JOY,The Cultist,INTRO,We are all just vibrations! I have transcended this fleshy prison!,,1,
JOY,The Cultist,WINNING,Let me cleanse your aura... WITH FIRE!,,1,
JOY,The Cultist,LOSING,My chakras... they are bleeding...,,1,
JOY,The Cultist,DEFEAT,The universe... lied to me...,,1,
JOY,The Influencer,INTRO,"A million followers, baby! Look at this view, look at this life!",,1,
JOY,The Influencer,WINNING,"SMILE FOR THE CAMERA, TRASH!",,1,
JOY,The Influencer,LOSING,I'm losing sponsors... I'm losing relevance...,,1,
JOY,The Influencer,DEFEAT,Did anybody... even like... the post?,,1,
JOY,The Pyromaniac,INTRO,Look at how pretty the flames are on the dumpsters! It's art!,,1,
JOY,The Pyromaniac,WINNING,BURN! EVERYTHING LOOKS BETTER IN RED!,,1,
JOY,The Pyromaniac,LOSING,The smoke... I can't breathe...,,1,
JOY,The Pyromaniac,DEFEAT,"Just embers... cold, dead embers...",,1,
SURPRISE,The Betrayed,INTRO,"Yesss YESSSS give me that sweet sweet nectar GIVE IT... wait, what did you just inject me with?",,1,
SURPRISE,The Betrayed,WINNING,I'LL TEAR THE POISON OUT OF YOUR CHEST!,,1,
SURPRISE,The Betrayed,LOSING,My heart... it's beating too fast...,,1,
SURPRISE,The Betrayed,DEFEAT,You... you killed me...,,1,
SURPRISE,The Accident,INTRO,The light was green! I swear on my mother's life the light was green!,,1,
SURPRISE,The Accident,WINNING,"You see it too, right? The glass in my hair?",,1,
SURPRISE,The Accident,LOSING,Why is the steering wheel bending like that?,,1,
SURPRISE,The Accident,DEFEAT,I can't... feel my legs...,,1,
SURPRISE,The Diagnosis,INTRO,"Six months? You're joking, right? I ran a marathon yesterday...",,1,
SURPRISE,The Diagnosis,WINNING,I'M NOT SICK! LOOK AT HOW STRONG I AM!,,1,
SURPRISE,The Diagnosis,LOSING,Why am I coughing blood...?,,1,
SURPRISE,The Diagnosis,DEFEAT,I don't have enough time...,,1,
SURPRISE,The Raid,INTRO,"They're breaking down the door! Throw it in the toilet, NOW!",,1,
SURPRISE,The Raid,WINNING,"YOU'LL NEVER TAKE ME ALIVE, PIGS!",,1,
SURPRISE,The Raid,LOSING,The window... it's too high up...,,1,
SURPRISE,The Raid,DEFEAT,Handcuffs... so cold...,,1,
SURPRISE,The Ghost,INTRO,Why won't anybody look at me? I've been screaming on this platform for hours...,,1,
SURPRISE,The Ghost,WINNING,FEEL ME! FEEL MY COLD HANDS!,,1,
SURPRISE,The Ghost,LOSING,My reflection... I don't have a reflection...,,1,
SURPRISE,The Ghost,DEFEAT,I died... I died under the metro...,,1,
ANGER,The Bailiff,INTRO,"I have the paper, I have the locks and I have all morning. OPEN IT.",STRONG,1,
ANGER,The Bailiff,WINNING,Everything in here belongs to someone else now. Including you.,STRONG,1,
ANGER,The Bailiff,LOSING,I'm just doing my job — I'M JUST DOING MY JOB!,STRONG,1,
ANGER,The Bailiff,DEFEAT,There's another twelve on the list today. Someone else will come.,STRONG,1,
ANGER,The Riot Line,INTRO,Disperse. You have been warned. YOU HAVE BEEN WARNED!,STRONG,1,
ANGER,The Riot Line,WINNING,Nobody filmed this. Nobody ever films this.,STRONG,1,
ANGER,The Riot Line,LOSING,Hold the line... hold the LINE...,STRONG,1,
ANGER,The Riot Line,DEFEAT,Badge number... nobody ever asks for the badge number.,STRONG,1,
ANGER,The Developer,INTRO,Forty families out by Friday and a rooftop pool by spring. Try and stop me.,STRONG,1,
ANGER,The Developer,WINNING,This whole barri is already sold. You're standing in a render.,STRONG,1,
ANGER,The Developer,LOSING,The permits — who talked to the press about the permits?!,STRONG,1,
ANGER,The Developer,DEFEAT,It was going to be beautiful...,STRONG,1,
SURPRISE,The Verdict,INTRO,All of it. They're keeping ALL of it. I signed — I SIGNED WHAT?!,STRONG,1,
SURPRISE,The Verdict,WINNING,"Read the small print, they said. READ IT NOW, GO ON!",STRONG,1,
SURPRISE,The Verdict,LOSING,There has to be an appeal. There's always an appeal...,STRONG,1,
SURPRISE,The Verdict,DEFEAT,Fourteen years. In one afternoon.,STRONG,1,
SURPRISE,The Blackout,INTRO,Whose jacket is this? WHOSE BLOOD IS THIS? Somebody tell me what I did!,STRONG,1,
SURPRISE,The Blackout,WINNING,You were there! You saw it! SAY WHAT YOU SAW!,STRONG,1,
SURPRISE,The Blackout,LOSING,"It's coming back... oh God, it's coming back...",STRONG,1,
SURPRISE,The Blackout,DEFEAT,Don't tell me. Please. Don't ever tell me.,STRONG,1,
SURPRISE,The Collapse,INTRO,The ceiling was there this morning. IT WAS THERE THIS MORNING!,STRONG,1,
SURPRISE,The Collapse,WINNING,Nothing holds! Look at it! NOTHING HOLDS!,STRONG,1,
SURPRISE,The Collapse,LOSING,My hands won't stop. Why won't my hands stop?,STRONG,1,
SURPRISE,The Collapse,DEFEAT,Everyone kept saying it was fine.,STRONG,1,
SADNESS,The Sleepless,INTRO,"Fourth night. The train's warm, that's all. Don't make me move.",WEAK,1,
SADNESS,The Sleepless,WINNING,You get used to the noise. You never get used to the light.,WEAK,1,
SADNESS,The Sleepless,LOSING,I only wanted to close my eyes...,WEAK,1,
SADNESS,The Sleepless,DEFEAT,Wake me at Fondo. Somebody always does.,WEAK,1,
SADNESS,The Unread Message,INTRO,"Delivered. Two blue ticks, eleven days ago. That's the whole story.",WEAK,1,
SADNESS,The Unread Message,WINNING,Everyone's busy. Everyone's always so busy.,WEAK,1,
SADNESS,The Unread Message,LOSING,Maybe she's just... maybe the phone...,WEAK,1,
SADNESS,The Unread Message,DEFEAT,I'll type it again tonight. I won't send it.,WEAK,1,
SADNESS,The Last One Out,INTRO,"Everybody left for Berlin, Lisbon, anywhere. I locked up.",WEAK,1,
SADNESS,The Last One Out,WINNING,You'll go too. They all go.,WEAK,1,
SADNESS,The Last One Out,LOSING,It's only me on this platform now...,WEAK,1,
SADNESS,The Last One Out,DEFEAT,Somebody has to stay and turn the lights off.,WEAK,1,
JOY,The Last Round,INTRO,"Six in the morning and the night's still GOING! Come on, one more, ONE MORE!",WEAK,1,
JOY,The Last Round,WINNING,This is living! THIS IS LIVING! Where's my phone?,WEAK,1,
JOY,The Last Round,LOSING,"Wait — wait, has anyone got water...",WEAK,1,
JOY,The Last Round,DEFEAT,I'll be fine. I've got work at nine. I'll be fine.,WEAK,1,
JOY,The Hen Party,INTRO,"Eleven of us, matching sashes, and NOBODY is going home sad tonight!",WEAK,1,
JOY,The Hen Party,WINNING,Smile! SMILE! It's meant to be the best day of her life!,WEAK,1,
JOY,The Hen Party,LOSING,Where's Marta? Has anyone seen Marta?,WEAK,1,
JOY,The Hen Party,DEFEAT,She cried in the toilets for an hour. We got the photos though.,WEAK,1,
JOY,The Busker,INTRO,Same four chords for nine years and the carriage still claps! Listen!,WEAK,1,
JOY,The Busker,WINNING,They're LOVING this! Look at them! They're loving it!,WEAK,1,
JOY,The Busker,LOSING,Two euros. Whole carriage. Two euros...,WEAK,1,
JOY,The Busker,DEFEAT,Next stop's better. Next stop's always better.,WEAK,1,
ANGER,The Terminus,INTRO,"End of the line. Everybody off. EVERYBODY OFF, I said!",BOSS,1,
ANGER,The Terminus,WINNING,Forty years I've turned this train around. You'll not be the one that stops me.,BOSS,1,
ANGER,The Terminus,LOSING,There's no more track. There's no more TRACK!,BOSS,1,
ANGER,The Terminus,DEFEAT,Somebody has to be here when it ends. It was always going to be me.,BOSS,1,
SURPRISE,The Comedown,INTRO,Wait. Wait — what time is it? What DAY is it? Who let the light in?!,BOSS,1,
SURPRISE,The Comedown,WINNING,"It's not over! It was never over! One more, come on, ONE MORE!",BOSS,1,
SURPRISE,The Comedown,LOSING,My heart's doing something. My heart's doing something wrong—,BOSS,1,
SURPRISE,The Comedown,DEFEAT,Take it. Take the lot. I never want to feel that good again.,BOSS,1,
JOY,The Line Manager,INTRO,Ohmygod hiii! Okay so — you're kind of ruining the vibe right now? Smile.,BOSS,1,
JOY,The Line Manager,WINNING,This city is literally MY brunch and you are literally not invited!,BOSS,1,
JOY,The Line Manager,LOSING,"No no no, this isn't — I don't DO bad days. Somebody fix this. FIX IT!",BOSS,1,
JOY,The Line Manager,DEFEAT,Fine. FINE. Keep your stupid little line. I'm moving to Lisbon anyway.,BOSS,1,
JOY,The Line Manager,PHASE2,You don't GET it. You can't beat me — I AM the good time. I am every rooftop in this city. I AM JOY.,BOSS,1,
JOY,The Line Manager,DEFEAT2,"...it was such a good year. It was such a good, good year.",BOSS,1,`,

/* --- rules ---
   global tunables, read by name.  */
rules: `key,value,description,,,
lineCap,3,"FALLBACK line size, used only if a unit row leaves line_cap blank.",,,
maxLayers,6,Layer slots per unit.,,,
restEc,15,Charge gained by departing with an empty line.,,,
ecBasis,POWER,POWER = charge figured from the ability's base power. DEALT = from damage actually dealt.,,,
noLayerDmgMult,1,Superseded by the matchups sheet; kept as a fallback.,,,
noLayerEcMult,0,Superseded by the matchups sheet; kept as a fallback.,,,
shieldRotatesLayer,0,Whether a blocked attack still rotates the layer queue.,,,
lowMsWarnPct,0.18,Below this fraction of max MS the ceiling chevron pulses red.,,,
clashSeconds,4,Length of the death sequence.,,,
layerRegenAtTurnEnd,1,"Broken layers stay gone until the round ends, then regrow at the back of the queue.",,,
chargeStepMs,260,How long each charge segment holds before the next.,,,
flyMs,120,How long a station takes to fly across and strike the target.,,,
typeMs,32,Delay between letters of dialogue.,,,
dialogueHoldMs,3000,How long a finished line stays on screen before it fades.,,,
lowHpTalkPct,0.2,Fraction of max MS below which the winning / losing lines fire.,,,
overloadSlotPer,0.25,Every this-much overflow (as a fraction of max MS) forces one more corrupted slot.,,,
aiVarietyChance,0.22,Chance the AI takes a random affordable attack instead of its best one.,,,
aiDebuffChance,0.5,Chance the AI spends a slot on a debuff the target is not already suffering.,,,
aiGrowChance,0.45,"How often the enemy takes an ADDLAYER ability when one is worth a slot. Like the debuff branch, this exists because the AI scores on damage per slot and a layer deals none - without it Bristle, Bile and Good Vibes sit in the pool and are never once chosen.",,,
aiChargeBias,0.55,Chance the AI prefers an ability with charge segments when it can afford one.,,,
shuffleLayersEachRound,1,Re-order every unit's layer queue at the start of each round.,,,
maxExtraSlots,6,Hard cap on extra slots of any kind a line may carry.,,,
loadoutPatternAlpha,0.13,How faint the emotion glyph tiled behind a Loadout button is.,,,
loadoutSlots,4,"Ability slots in one Loadout, and so cells per page.",,,
equippedSlots,3,Loadouts the player carries into a battle.,,,
slotArriveMs,260,Gap between one temporary slot flying in and the next.,,,
impactFlashMs,45,White frame on a hit.,,,
impactShakeMs,85,Shake after that white frame.,,,
stunTurns,1,Turns a unit is stunned for once its last layer breaks. It skips its line and regrows nothing.,,,
lineTravelMs,200,How long the line takes to slide the next station to the centre.,,,
lineFlashMs,90,How long a centred station flashes before it strikes.,,,
chargeShownMax,2,Most charge stations drawn in an ability box; beyond this it just repeats.,,,
critChance,0.05,"Default chance an attack crits, when the ability does not say otherwise.",,,
frameMaxW,420,The phone frame's widest; nothing drawn for it may exceed this.,,,
momentPx,2,Upscale of the title screen's mood line: bigger = chunkier pixels.,,,
momentSize,10,LOGICAL type size; what you see is this times momentPx.,,,
critTagMs,700,How long a plain positioned tag stays up.,,,
critHoldMs,1000,How long CRITICAL is held before the earned slot flies in.,,,
critFlashMs,260,One wash of the screen in the attacking emotion's colour.,,,
critSlotFlyMs,520,The earned slot travelling from the tag to the line.,,,
critMult,2,Damage multiplier on a critical.,,,
statusStepMs,2000,"A station that applies a status holds this long, so it can be read.",,,
attackStepMs,600,"Total time one executed station takes, start to finish.",,,
lineAlertFlashes,3,How many times a line flashes white before it starts executing.,,,
lineAlertMs,110,Length of one of those flashes.,,,
unsheathMs,340,How long one interface element takes to draw itself into place.,,,
unsheathGapMs,110,"Gap before the next element starts — smaller than unsheathMs, so they overlap.",,,
longPressMs,420,How long an ability must be held before its tooltip opens.,,,
swipeMinPx,36,How far a pointer must travel across the panel to count as a page swipe.,,,
tagGrowth,0.85,How much an accumulating tag grows once it holds a full max-MS worth of change.,,,
tagBreathSlowMs,1700,Breathing period of an accumulating tag holding almost nothing.,,,
tagBreathFastMs,380,Breathing period of a tag holding a full max-MS worth — it flashes far harder.,,,
gaugeW,134,"Gauge canvas width in logical pixels. Lower = chunkier pixels, coarser value steps.",,,
gaugeH,22,Gauge canvas height in logical pixels — tall enough for the end caps.,,,
barCoreH,12,"Height of the bar's interior, before the wave, in logical pixels.",,,
barWaveAmp,1.4,Wave amplitude on the bar's silhouette (reference: 9.8 of a 1026-long bar).,,,
barWaveHalf,5.6,"Half-period of the silhouette wave, i.e. one arc (reference: 43.3).",,,
barWaveSpeed,0.1,How fast the silhouette wave travels.,,,
ecBandFrac,0.82,Charge fill height as a fraction of the bar interior (reference: 76 of 92.74).,,,
ecWaveAmp,0.7,"Amplitude of the charge fill's own wave — long and shallow, per the reference.",,,
ecWaveHalf,19,Half-period of the charge fill's wave. Much longer than the silhouette's.,,,
ecWaveSpeed,0.05,How fast the charge wave travels.,,,
ecInnerFrac,0.5,"Inner charge bar thickness, as a fraction of the outer one. Same shape, dodged over it.",,,
ecInnerAmt,0.4,How hard the inner charge bar dodges. 1 blows out to white; lower keeps the hue.,,,
arcSpacing,3.1,Spacing of the background arc texture (reference: 23.83).,,,
arcRadius,12.6,Radius of the background arcs (reference: 96.95).,,,
arcAlpha,0.11,How strongly the arcs show. They only read against the unlit stretch.,,,
capW,5,End-cap width in logical pixels.,,,
capR,2,End-cap corner rounding in logical pixels.,,,
ballFlyMs,330,How long a ball of light takes to arc from its indicator into the bar.,,,
settleStepMs,70,Pause between one hit landing on a bar and the next setting off.,,,
fnumMinPx,20,Smallest a floating damage number gets.,,,
fnumMaxPx,62,Largest — reached when one hit costs a whole stamina bar.,,,
fnumRisePx,34,How far a floating number travels up before it settles.,,,
fnumInMs,600,Fade in while rising.,,,
fnumHoldMs,600,Easing to a stop.,,,
fnumOutMs,400,Fade out.,,,
fnumLingerMs,300,Extra time a floating number holds before it goes.,,,
hitShards,3,Shapes thrown off where an attack lands.,,,
hitShardMs,260,How long one of those shapes flashes.,,,
actionLineMs,620,Buff / debuff streaks over the target.,,,
statusFxMs,1000,Distortion and bloom when a status takes hold.,,,
backdropGlow,0.55,How strongly the enemy's emotion tints the battle backdrop.,,,
barTweenMs,1000,How long a bar takes to travel to its new value once a hit lands.,,,
overloadHoldMs,2000,How long the OVERLOAD tag and its slow motion last.,,,
ecScrollSpeed,0.0044,How fast the charge gradient drifts along the bar.,,,
themeOpening,audio/theme-opening.wav,Theme part 1: plays once.,,,
themeLoop,audio/theme-loop.wav,"Theme part 2: loops for ever, scheduled to start the instant part 1 ends.",,,
musicFadeMs,900,How quickly the theme fades out when the battle ends.,,,
musicVolume,1.6,"Theme level, and ABOVE 1 on purpose: this is a gain, not a percentage. The battle theme is mastered about 10 dB quieter than the map's two, so it needs lifting to sit level with them - measured busy RMS -20.1 dBFS against -9.2 and -10.6, all three now landing at -16.0. Its peak is -5.2 dBFS, so 1.6x leaves headroom and cannot clip. Lower this if the sound effects are getting buried.",,,
sfxVolume,1.05,"Sound-effect level, mixed against musicVolume.",,,
layerEase,0.16,How fast layers slide to their new slot. Higher = snappier.,,,
layerWaveDelay,0.85,"Phase offset per slot, so breathing travels outward in waves.",,,
layerInnerShrink,0.85,Curve of the radius falloff toward the centre.,,,
layerFill,0.42,Ring thickness as a fraction of the gap to the next slot.,,,
layerOuterThick,2,Thickness multiplier for the outermost (active) layer.,,,
layerInnerThick,0.9,Thickness multiplier for every layer behind it.,,,
layerFlashMs,50,How long a struck layer flashes white before vanishing.,,,
layerGapMs,18,Beat between the layer vanishing and it regrowing at the back.,,,
layerRegrowMs,380,How long the regrow beat holds before resolution continues.,,,
enemyRingBaseR,28,"Enemy: radius of the outermost ring, in logical canvas pixels.",,,
enemyShapeWeak,TRIANGLE,Battle silhouette for a WEAK enemy: its layer rings are concentric TRIANGLES.,,,
enemyShapeRegular,CIRCLE,"Battle silhouette for a REGULAR enemy. The original, and still the default for any tier the sheet does not name.",,,
enemyShapeStrong,STAR,Battle silhouette for a STRONG enemy: concentric stars of enemyStarPoints points.,,,
enemyStarPoints,7,Points on a STRONG enemy's star.,,,
enemyStarInner,0.62,"A star's valley radius as a fraction of its point radius. LOWER = narrower, sharper points; HIGHER = a blunter, rounder star. Below about 0.45 the thin inner rings start breaking up at this canvas size.",,,
enemyShapeFill,1.6,"Band thickness multiplier for a SHAPED enemy only (triangle or star), on top of layerFill. A shape squeezes every band's pixel thickness by how narrow it is at that angle, and at the default the thin inner rings fell under one pixel and broke into dashes. THERE IS A CEILING AS WELL AS A FLOOR: at 2.0 the gaps between bands drop under a pixel and the rings merge into one solid shape, which is a filled triangle rather than concentric ones. Circles are not affected.",,,
enemyShapeBreathe,0.6,"How much of the usual ring breathing a SHAPED enemy does. Full amplitude closes the gap between two neighbouring bands, and with the thicker bands above that swallows one of them. Together with enemyShapeFill this is what keeps every ring continuous at every angle - see tools/check_rings.js.",,,
enemyTriRound,0.72,"How far a WEAK enemy's triangle goes toward a TRUE triangle: 1 is sharp corners, 0 is a circle. It is not there to soften the look - a true triangle squeezes the thin inner rings under one pixel near the flat sides and they disappear.",,,
enemyShapeSpin,0.018,Radians per frame a triangle or a star turns. A polygon that never moves reads as a logo; a slow turn reads as a creature. 0 stops it.,,,
enemyRingScaleWeak,0.85,"Overall size of a WEAK enemy in battle, against a REGULAR one.",,,
enemyRingScaleStrong,1.05,Overall size of a STRONG enemy in battle. Do not raise much: the canvas is 64px and the rings breathe outward past this.,,,
rideScaleWeak,0.78,"How big a WEAK enemy is during a ride, against its element row's own size. Do not go much lower: below about nine pixels across, three points stop reading as a triangle and it is just a small blob.",,,
rideScaleStrong,1.55,How big a STRONG enemy is during a ride. Size is the tier cue that survives being glanced at; the silhouette is the one that survives being looked at.,,,
enemyRingSpacing,4.7,Enemy: radius step between one layer and the next in. baseR/spacing sets how many fit.,,,
enemyRingBreathe,1.6,Enemy ring breathing amplitude.,,,
playerRingBaseR,300,Player: radius of the outermost ring. Huge on purpose — a big circle reads as a nearly flat band.,,,
playerRingSpacing,5,"Player: radius step between layers. Small, so all six sit in a thin arc despite the huge radius.",,,
playerRingBreathe,2.2,Player ring breathing amplitude.,,,
playerCanvasW,120,Player ring canvas width in logical pixels (wide and short).,,,
playerCanvasH,32,Player ring canvas height in logical pixels.,,,
playerRingCy,300,"Player: circle centre Y, pushed far below the strip so only the flat top of the arc shows.",,,
crusherSteps,12,"Audio bit-crusher quantisation. Low = Atari harsh, high = SNES-clean.",,,
travelRollSecs,3,Legacy fixed roll interval. rollMinSecs/rollMaxSecs supersede it.,,,
travelTarget,10,Legacy fixed segment target. segBase x diltransience supersedes it.,,,
travelTapR,15,"FLOOR for how near a tap must land on a travel element, in art pixels. The real reach is the element's own size scaled up; this is the minimum.",,,
segBase,5,"Track Segments to bridge a link, before diltransience and world state.",,,
rollMinSecs,1,Fastest the track event roll can come round (navigation GDD 4: every 1-3s).,,,
rollMaxSecs,3,Slowest the track event roll can come round. Enemy density moves it.,,,
aggroLockSecs,5,Default countdown before an aggro enemy forces the encounter.,,,
travelMaxLive,5,"How many elements may be out at once, ALL KINDS TOGETHER. No roll happens while the board is full, so it has to clear before anything new appears.",,,
tripFillMs,520,How long the Emotional Trip bar takes to ease across to a newly collected segment.,,,
tripFlashMs,260,How long the bar flashes white when a segment lands in it.,,,
departSecs,3,How long the camera spends zooming into the departure station before the wipe opens.,,,
leanEaseMs,520,"How long the map takes to tilt into, and back out of, the focused-station lean.",,,
leanDeg,20,How far the map tilts when a destination is being considered.,,,
camEaseMs,620,How long the camera takes to travel to a station the player has just picked.,,,
orbMsPct,0.18,"How much of MaxMS one Stamina Orb gives back. Orbs only matter mid-ride, which is the only time MS moves.",,,
encounterWashSecs,1.1,How long the travel screen floods with the enemy's colour before the wipe onto the fight.,,,
battleWipeMs,820,The circular wipe that opens onto the battle.,,,
battleFadeMs,620,The fade to white that unloads the battle and gives the ride back.,,,
musicCutMs,120,The ultra-quick fade that kills the battle theme the moment an enemy falls.,,,
enterWipeMs,1100,The circular wipe that opens the map when arriving from the title screen.,,,
exitKeepPct,0.6,Crystals kept when EXITING at an intermediate platform.,,,
defeatKeepPct,0.1,Crystals kept on defeat.,,,
itemLossOnExit,0.4,Chance each unbanked item is lost when exiting early.,,,
itemLossOnDefeat,0.9,Chance each unbanked item is lost on defeat.,,,
fogPeekHide,1.6,Fog at or above this hides a station's details from the map.,,,
startLineKeys,L1|L2,Line Keys the player begins with.,,,
affinitySlots,2,How many Emotional Affinities a player picks at creation.,,,
armorSlots,1,Emotional Armor pieces worn at once.,,,
startArmor,ARM_SCARS,The armor a new profile begins in.,,,
startSets,LO_ANGER|LO_SADNESS|LO_JOY|LO_DISGUST|LO_SURPRISE,"The Move Sets a profile OWNS. \`equippedSlots\` of them can be carried at once, so this is the shelf to pick from rather than the loadout itself.",,,
startArmorOwned,ARM_SCARS|ARM_STATIC,"Armor a profile OWNS, beyond the one it is wearing. Same idea as startSets.",,,
joltEc,20,Emotional Charge the Set of Jolt's passive returns each time one of your attacks misses.,,,
critSlots,1,"Extra line slots a critical earns, for anyone without a passive that says otherwise. The slot is good for exactly one line.",,,
rushCritSlots,3,"What PAS_RUSH (the Set of Rush) turns that into. Raising it raises the ceiling of the whole set, which is the one number worth balancing it on.",,,
objectiveWobble,0.9,"How far an objective's marker swings, in map pixels. It is a wobble, not an orbit: the ? never leaves the top of its station.",,,
objectiveBeatMs,760,"Period of the white circle's beat, in ms. One breath per station, so a screen of them does not pulse in lockstep - each is offset by a hash of its own id.",,,
aggroChance,0.25,"Fraction of the enemies that appear on a ride which LOCK ON and count down to forcing the fight. Multiplied by the target station's own aggro, so a hostile stretch of network really is more hostile. 0 turns the whole behaviour off.",,,
aggroTiers,WEAK|REGULAR,"Which tiers may lock on. A STRONG enemy is deliberately not on this list: a hard fight you did not choose is a punishment, and the one thing that makes a strong enemy fair is that taking it on is a decision.",,,
aggroRingThick,2,"Thickness, in art pixels, of the countdown ring drawn around a locked-on enemy.",,,
aggroWarnHz,4.5,How many times a second the warning sign above a locked-on enemy flashes.,,,
mapShakeMs,420,How long the ride screen shakes when a fight starts.,,,
mapShakeAmp,7,"How far the ride screen is thrown, in CSS pixels, at the start of that shake. It decays to nothing over mapShakeMs.",,,
guardianWarnMs,3000,How long the banner announcing the station's Guardian Entity holds before the fight begins on its own.,,,
fleeHoldMs,3000,How long a press has to be held on the battle arena before the ring closes and the fight is abandoned.,,,
fleeSegmentCost,5,"Track Segments forfeited every time a fight is run from. Taken off the current ride's progress, never below zero.",,,
bossPhaseAt,0.2,Fraction of MaxMS at which a LINE MANAGER refuses to fall and takes her second wind. She cannot be killed below this until it has happened.,,,
bossPhaseTo,0.5,What she recovers to.,,,
bossRechargeMs,5000,How long that recovery takes. Deliberately long: it is the fight being taken away from you and handed back.,,,
bossFlashes,4,"White flashes before the recovery, and again when it completes.",,,
bossSinkMs,7000,"How long a beaten LINE MANAGER takes to shake, sink and fade off the bottom of the screen.",,,
bossHushMs,520,How quickly the music and the interface go when she refuses to fall.,,,`,

/* --- sounds ---
   synthesised at runtime, no audio files. wave: square|sawtooth|triangle|sine|noise.  */
sounds: `id,wave,f0,f1,dur,gain,echo,description
tap,square,980,1460,80,0.46,0.3,Adding an ability to the line.
place,square,620,1760,130,0.4,0.35,The station lands on your line and flashes white.
resist,square,880,760,120,0.34,0.3,"A layer shrugs off its own emotion. Played twice, descending."
hit_anger,square,300,90,150,0.36,0.28,Anger lands: hard and low.
hit_surprise,sawtooth,1200,300,130,0.3,0.34,Surprise lands: a sharp drop.
hit_disgust,noise,420,200,180,0.3,0.3,Disgust lands: wet and dull.
hit_joy,square,900,1800,120,0.3,0.32,Joy lands: bright and rising.
hit_sadness,triangle,520,180,220,0.3,0.38,Sadness lands: a long fall.
hit_fear,noise,900,1400,120,0.26,0.4,Fear lands: a cold hiss.
buff_up,square,420,1500,260,0.28,0.35,Something is lifted.
debuff_down,sawtooth,1500,260,300,0.3,0.38,Something is dragged down.
status_on,noise,200,1100,520,0.32,0.5,A status takes hold.
sheatheE,sawtooth,1500,220,150,0.3,0.22,Enemy UI element drawn into place. Lower.
sheatheP,sawtooth,2100,340,140,0.28,0.22,Player UI element drawn into place. Higher.
slot,triangle,300,1500,150,0.3,0.45,A temporary slot flies in from the opponent.
remove,square,520,220,90,0.34,0.24,Removing a station.
depart,sawtooth,240,70,420,0.26,0.45,The line departs and charge is spent.
travel,square,150,150,38,0.1,0.15,Line scrolling to the next station.
arrive,square,880,880,45,0.14,0.3,Station reaches the head and lights up.
hit,noise,700,700,190,0.34,0.4,Off-type hit.
absorb,square,300,1200,260,0.24,0.5,Same-type hit: the layer absorbs it.
block,noise,1600,1600,90,0.3,0.35,"Shield blocks, or shield goes up."
breaklayer,sawtooth,760,80,340,0.28,0.55,A layer flashes and breaks.
regrow,triangle,120,520,300,0.16,0.4,The broken layer regrows at the back.
clash,noise,240,240,1500,0.4,0.65,Death: the chevrons meet.
speak,square,620,540,42,0.09,0.12,One letter of dialogue appearing.
win,square,440,1320,620,0.24,0.55,Victory.
lose,sawtooth,320,50,950,0.28,0.6,Defeat.
map_select,square,760,1180,70,0.3,0.25,MAP: an adjacent station is chosen.
map_depart,sawtooth,180,900,620,0.3,0.5,MAP: the wipe opens and the train pulls away.
map_clack,square,210,150,34,0.13,0.18,MAP: one rail joint passing under the train.
map_announce,triangle,520,1040,300,0.26,0.4,MAP: 'Propera parada' over the carriage speaker.
map_flash,noise,300,2600,700,0.34,0.55,"MAP: the white flood, the train leaving the frame."
map_arrive,square,660,1980,540,0.26,0.45,MAP: the station banner lands.
map_return,sawtooth,1300,260,560,0.24,0.42,MAP: the wipe closes back onto the map.
map_step,triangle,900,1350,90,0.2,0.22,MAP: the player marker moving one station.
map_pick,square,1180,1760,70,0.26,0.2,MAP: a Track Segment is grabbed.
map_collect,square,880,2200,150,0.28,0.35,MAP: it lands in the Emotional Trip bar.
map_entity,noise,520,240,180,0.28,0.45,MAP: an Emotional Entity is prodded.
ui_tap,square,900,1240,52,0.22,0.14,MAP: a button.
ui_open,square,520,1180,120,0.24,0.28,MAP: a panel comes up.
ui_close,square,1180,520,110,0.2,0.22,MAP: a panel goes away.
ui_page,square,760,1010,60,0.18,0.16,MAP: moving between tabs.
ui_equip,square,640,1560,170,0.26,0.32,MAP: something is put on.
ui_deny,sawtooth,340,180,150,0.24,0.2,"MAP: refused - not owned, no route, no key."
map_screech,sawtooth,3200,240,520,0.5,0.55,"MAP: a fight starts. Violent, and the same sound whether the enemy forced it or you did - what it marks is the moment the ride stops being a ride."
boss_charge,sawtooth,90,1500,4600,0.34,0.3,"BATTLE: a Line Manager pulling her stamina back up. Long and rising, the length of the recovery itself."
boss_roar,sawtooth,1400,120,900,0.52,0.6,BATTLE: a Line Manager refusing to fall.
flee_hold,square,300,1300,3000,0.16,0.22,BATTLE: the escape ring closing under a held finger. Quiet and rising - it has to be audible under three seconds of nothing happening without becoming the loudest thing in the fight.
flee_go,noise,1800,200,420,0.4,0.5,BATTLE: the ring closes and the fight is abandoned.
map_tripup,sine,520,880,180,0.22,0.18,A segment lands in the Emotional Trip bar. Soft and rising — the one sound in the ride that is a reward rather than a click.
ui_station,triangle,680,1180,140,0.24,0.34,MAP: a station panel opens.`,

/* --- status_effects ---
   one row per status. Abilities apply these by id via status_apply.
   block_regen = layers held down; miss_chance = attacks the victim fluffs;
   self_hits = the victim turns one of its own attacks on itself each turn.  */
status_effects: `id,name,duration,icon,color,blurb,block_regen,miss_chance,self_hits,crit_mult,dmg_taken_mult,dmg_dealt_mult,ec_gain_mult,ms_per_turn,ec_per_turn,blocks_actions,stacking,max_stacks,enabled,notes
NO_REGEN,Rotting,2,ROT,#56a36a,*2* of your broken {LAYERS} are being held down. They stay broken until this wears off.,2,0,0,0,1,1,1,0,0,0,REFRESH,1,1,Holds this many broken layers down: they stay broken while it lasts.
SAD,Sad,2,DROP,#3d66c1,At the end of every round one of your own attacks is turned *on yourself*.,0,0,1,0,1,1,1,0,0,0,REFRESH,1,1,Each round end the victim turns one of its OWN attacks on itself.
OVERLOAD,Overload,0,WARN,#e53859,Your {EC} is over your {MS}. Your line is being invaded until you burn it down.,0,0,0,0,1,1,1,0,0,0,REFRESH,1,1,"DERIVED, not timed: it lasts while ec > ms, so it is never stored in unit.statuses."
BLINDED,Blinded,2,EYE,#e53859,{ANGER} has blotted out your aim. *Half* of your attacks miss outright.,0,0.5,0,0,1,1,1,0,0,0,REFRESH,1,1,The victim fluffs this fraction of its attacks.
RATTLED,Rattled,2,BURST,#724082,{SURPRISE} came from nowhere. *A third* of your attacks go wide.,0,0.35,0,0,1,1,1,0,0,0,REFRESH,1,1,"Surprise's own miss status. missChance() takes the HIGHEST of everything on a unit rather than summing, so Rattled and Blinded together are just Blinded."
DIZZY,Dizzy,1,BURST,#9a6bb0,The carriage is still moving without you. *Half* of your attacks miss outright.,0,0.5,0,0,1,1,1,0,0,0,REFRESH,1,1,"Blinded's miss rate for a SINGLE turn - what Drug Hit leaves behind. The whole difference between this and BLINDED is how long you live with it, which is what makes a one-turn status worth costing as a basic attack rather than as a debuff."`,

/* --- moments ---
   title-screen mood line. day is MON..SUN or *; hours are BARCELONA local,
   to_hour exclusive, and a band may wrap past midnight. Highest priority wins.  */
moments: `id,day,from_hour,to_hour,phrase,priority,enabled,notes
dawn_1,*,5,7,the first light is still deciding,0,1,
dawn_2,*,5,7,nobody has spoken yet today,0,1,
morn_1,*,7,10,early morning,0,1,
morn_2,*,7,10,the early carriages are full of unfinished sleep,0,1,
morn_3,*,7,10,everyone is already late,0,1,
mid_1,*,10,13,middle of the day,0,1,
mid_2,*,10,13,the light is flat and honest,0,1,
noon_1,*,13,16,all afternoon ahead,0,1,
noon_2,*,13,16,the long slow part of the day,0,1,
late_1,*,16,19,the afternoon is running out,0,1,
late_2,*,16,19,everyone is going somewhere they did not choose,0,1,
dusk_1,*,19,21,somber twilight,0,1,
dusk_2,*,19,21,the hour the day admits what it was,0,1,
night_1,*,21,24,the night is getting loud,0,1,
night_2,*,21,24,the last trains are filling up,0,1,
small_1,*,0,5,"the madrugada, and still moving",0,1,
small_2,*,0,5,too late to be anything but honest,0,1,
mon_morn,MON,5,10,"monday, and the week already weighs something",2,1,
mon_dusk,MON,19,24,the longest monday of the month,2,1,
wed_mid,WED,10,16,the week is stuck exactly in the middle,2,1,
thu_late,THU,16,21,"almost, but not yet",2,1,
fri_dusk,FRI,19,21,a night to finally be free,2,1,
fri_night,FRI,21,24,a night to finally be free,2,1,
fri_small,FRI,0,5,friday refusing to end,2,1,
sat_mid,SAT,10,16,a saturday with nothing owed to anyone,2,1,
sat_night,SAT,21,24,the city is pretending it never has to work again,2,1,
sun_mid,SUN,10,16,a sunday that stretches too far,2,1,
sun_dusk,SUN,19,24,"sunday dusk, and monday already breathing on it",2,1,`,

/* --- loadouts ---
   one Loadout per emotion. Slots are positional and a blank slot is a real
   empty slot in the panel. A Loadout may hold any ability whose emotion set
   includes its own emotion (see abilities.emotions).  */
loadouts: `id,emotion,name,slot1,slot2,slot3,slot4,tier,ec_mod,passive,cost,trade_in,enabled,notes
LO_ANGER,ANGER,Anger,ATK_ANGER,HVY_ANGER,GEN_ANGER,,1,0,,,,1,
LO_SADNESS,SADNESS,Sadness,ATK_SADNESS,HVY_SADNESS,INFLICT_SAD,,1,0,,,,1,
LO_JOY,JOY,Joy,ATK_JOY,HVY_JOY,GEN_JOY,,1,0,,,,1,
LO_DISGUST,DISGUST,Disgust,GEN_DISGUST,ROT,,,1,0,,,,1,
LO_SURPRISE,SURPRISE,Jolt,MID_SURPRISE,,,,1,0,PAS_JOLT,,,1,"One attack and one passive, deliberately. Surprise is not about volume of swings - it is about what happens when one goes wrong, which is what PAS_JOLT turns into charge."
LO_RUSH,SURPRISE,Rush,DRUG_HIT,,,,3,0,PAS_RUSH,,,1,Sant Antoni's reward. Its passive turns every critical into rushCritSlots extra slots instead of critSlots - three instead of one - so a set that offers one attack is really offering a bigger line whenever a hit goes well.
LO_FEAR,FEAR,Fear,,,,,1,0,,,,1,No Fear abilities exist yet.`,

/* --- prompts ---
   the cue above the attack line; one is drawn at random each turn.  */
prompts: `id,text,enabled,notes,,
p01,Whatcha gonna do?,1,,,
p02,How did that make you feel?,1,,,
p03,Act!,1,,,
p04,R U OK?,1,,,
p05,Show them.,1,,,
p06,Say something.,1,,,
p07,Your move.,1,,,
p08,Don't just stand there.,1,,,
p09,Feel it.,1,,,
p10,What now?,1,,,
p11,Answer that.,1,,,
p12,Let it out.,1,,,
p13,Breathe. Then act.,1,,,
p14,You alright?,1,,,
p15,Do something.,1,,,`
};

/* --- CSV reader: handles quoted fields, so notes may contain commas ---- */
function splitCSVLine(line){
  const out=[]; let cur="", q=false;
  for(let i=0;i<line.length;i++){
    const c=line[i];
    if(q){
      if(c==='"'){ if(line[i+1]==='"'){cur+='"'; i++;} else q=false; }
      else cur+=c;
    }else{
      if(c==='"') q=true;
      else if(c===",") { out.push(cur); cur=""; }
      else cur+=c;
    }
  }
  out.push(cur); return out;
}
function parseCSV(src){
  const lines = src.trim().split(/\r?\n/).filter(l=>l.trim()!=="");
  const head = splitCSVLine(lines.shift()).map(h=>h.trim());
  return lines.map(line=>{
    const cells = splitCSVLine(line);
    const row = {};
    head.forEach((h,i)=>{
      let v = (cells[i]??"").trim();
      if(SCHEMA.list.includes(h))      row[h] = v ? v.split("|").map(s=>s.trim()) : [];
      else if(SCHEMA.bool.includes(h)) row[h] = v==="1"||v.toUpperCase()==="TRUE";
      else if(v!=="" && !isNaN(Number(v))) row[h] = Number(v);
      else row[h] = v;
    });
    return row;
  });
}
const byId = rows => Object.fromEntries(rows.map(r=>[r.id,r]));

const EMOTIONS  = byId(parseCSV(DATA.emotions));
const ABILITIES = byId(parseCSV(DATA.abilities));
const UNITS     = byId(parseCSV(DATA.units));
const RULES     = Object.fromEntries(parseCSV(DATA.rules).map(r=>[r.key,r.value]));
const SOUNDS    = byId(parseCSV(DATA.sounds));
const MATCHUPS  = parseCSV(DATA.matchups);
const DIALOGUE  = parseCSV(DATA.dialogue);
const STATUSES  = byId(parseCSV(DATA.status_effects).filter(r=>r.enabled));
const MOMENTS   = parseCSV(DATA.moments).filter(r=>r.enabled);
const LOADOUTS  = byId(parseCSV(DATA.loadouts).filter(r=>r.enabled));
const PROMPTS   = parseCSV(DATA.prompts).filter(r=>r.enabled);
