#!/usr/bin/env python3
"""
Convert a .mid into music.js — a plain note list the prototype's own WebAudio
synth plays back. No MIDI parsing happens in the browser, and no audio file is
fetched, so it works from file:// as well as from a server.

    python3 tools/build_music.py "Theme Song 8_bit.mid"

Track names decide the voice. Edit VOICES to remap.
"""
import sys, os, json, struct

VOICES = {                       # substring of the track name -> (wave, gain)
    "lead":   ("square",   0.16),
    "rythm":  ("square",   0.07),
    "rhythm": ("square",   0.07),
    "bass":   ("triangle", 0.20),
    "drum":   ("noise",    0.16),
    "string": ("triangle", 0.08),
    "saw":    ("sawtooth", 0.07),
}
DEFAULT = ("square", 0.09)

def vlq(b, p):
    v = 0
    while True:
        c = b[p]; p += 1; v = (v << 7) | (c & 0x7F)
        if not c & 0x80:
            return v, p

def parse(path):
    d = open(path, "rb").read()
    if d[:4] != b"MThd":
        sys.exit("! not a MIDI file")
    fmt, ntrk, div = struct.unpack(">HHH", d[8:14])
    if div & 0x8000:
        sys.exit("! SMPTE time division is not supported")

    chunks, i = [], 14
    while i < len(d) - 8:
        cid = d[i:i+4]; ln = struct.unpack(">I", d[i+4:i+8])[0]
        chunks.append((cid, i + 8, ln)); i += 8 + ln

    # tempo map first: (tick, microseconds per quarter note)
    tempos = []
    for cid, off, ln in chunks:
        if cid != b"MTrk": continue
        p, end, tick, last = off, off + ln, 0, None
        while p < end:
            dt, p = vlq(d, p); tick += dt
            st = d[p]
            if st & 0x80: last = st; p += 1
            else: st = last
            if st == 0xFF:
                mt = d[p]; p += 1; l, p = vlq(d, p)
                if mt == 0x51: tempos.append((tick, struct.unpack(">I", b"\x00" + d[p:p+3])[0]))
                p += l
            elif st in (0xF0, 0xF7):
                l, p = vlq(d, p); p += l
            else:
                p += 1 if (st & 0xF0) in (0xC0, 0xD0) else 2
    tempos.sort()
    if not tempos: tempos = [(0, 500000)]

    def tick_to_sec(t):
        sec, prev_tick, upq = 0.0, 0, tempos[0][1]
        for tt, uu in tempos:
            if tt >= t: break
            sec += (tt - prev_tick) / div * (upq / 1e6)
            prev_tick, upq = tt, uu
        return sec + (t - prev_tick) / div * (upq / 1e6)

    out, total = [], 0.0
    for cid, off, ln in chunks:
        if cid != b"MTrk": continue
        p, end, tick, last = off, off + ln, 0, None
        name, notes, on = "", [], {}
        while p < end:
            dt, p = vlq(d, p); tick += dt
            st = d[p]
            if st & 0x80: last = st; p += 1
            else: st = last
            if st == 0xFF:
                mt = d[p]; p += 1; l, p = vlq(d, p)
                if mt in (0x03, 0x04) and not name:
                    name = d[p:p+l].decode("latin1", "replace").strip()
                p += l
            elif st in (0xF0, 0xF7):
                l, p = vlq(d, p); p += l
            else:
                hi = st & 0xF0
                if hi == 0x90:
                    n, v = d[p], d[p+1]; p += 2
                    if v > 0: on.setdefault(n, []).append((tick, v))
                    else:
                        st_list = on.get(n)
                        if st_list:
                            t0, v0 = st_list.pop(0)
                            notes.append((t0, tick, n, v0))
                elif hi == 0x80:
                    n = d[p]; p += 2
                    st_list = on.get(n)
                    if st_list:
                        t0, v0 = st_list.pop(0)
                        notes.append((t0, tick, n, v0))
                else:
                    p += 1 if hi in (0xC0, 0xD0) else 2
        if not notes: continue
        low = name.lower()
        wave, gain = DEFAULT
        for key, vg in VOICES.items():
            if key in low: wave, gain = vg; break
        rows = []
        for t0, t1, n, v in sorted(notes):
            a, b = tick_to_sec(t0), tick_to_sec(t1)
            dur = max(0.03, b - a)
            total = max(total, b)
            rows.append([round(a, 3), round(dur, 3), n, round(v / 127, 2)])
        out.append({"name": name or "track", "wave": wave, "gain": gain, "notes": rows})
    return out, round(total + 0.6, 3)

def main():
    if len(sys.argv) < 2: sys.exit(__doc__)
    src = sys.argv[1]
    tracks, length = parse(src)
    here = os.path.dirname(os.path.abspath(__file__))
    dst = os.path.join(here, "..", "music.js")
    js = ("/* GENERATED by tools/build_music.py from " + os.path.basename(src) + "\n"
          "   Notes are [startSeconds, durationSeconds, midiNote, velocity0to1].\n"
          "   Played by the prototype's own WebAudio synth — no audio file involved. */\n"
          "const MUSIC = " + json.dumps({"length": length, "tracks": tracks},
                                        separators=(",", ":")) + ";\n")
    open(dst, "w", encoding="utf-8").write(js)
    n = sum(len(t["notes"]) for t in tracks)
    print(f"wrote music.js — {len(tracks)} tracks, {n} notes, {length}s loop, "
          f"{os.path.getsize(dst)//1024} KB")
    for t in tracks:
        print(f"   {t['name']:<16} {t['wave']:<9} gain {t['gain']}  {len(t['notes'])} notes")

if __name__ == "__main__":
    main()
