#!/usr/bin/env python3
"""
Regenerate data.js from spreadsheet CSV exports.

    python3 tools/build_data.py <folder-of-csvs>

In Google Sheets: File > Download > Comma-separated values, once per sheet.
Google names them like "battle-system-config - abilities.csv"; this matches on the part
after the last " - ", so you can drop the whole export folder in as-is.

Sheets that are reserved (layer_types, synergies) and the README/checks sheets
are ignored — nothing reads them yet.
"""
import sys, os, glob, re, csv, io

TABLES = ["emotions", "abilities", "matchups", "units", "dialogue", "rules", "sounds",
          "status_effects", "moments", "loadouts", "prompts"]

# spreadsheet-side balancing helpers — meaningless at runtime, so they are
# stripped rather than shipped into data.js
DROP_COLUMNS = {"suggested_cost", "cost_delta"}
HERE   = os.path.dirname(os.path.abspath(__file__))
OUT    = os.path.join(HERE, "..", "data.js")

HEADER_COMMENTS = {
 "emotions":  "one row per emotion. `token` maps to the CSS palette variable.",
 "abilities": "kind DAMAGE|SHIELD · power = damage or shield charges · blank emotion = typeless\n   (never matches a layer) · hits_layer = whether a hit rotates the target's queue.",
 "matchups":  "attack emotion x layer emotion. '*' is a wildcard, 'NONE' means the target has\n   no layers. Highest priority wins, so a specific pair always beats a wildcard.\n   Adding a synergy is adding a row.",
 "units":     "layers are outermost-first and rotate as they take hits. pool = usable abilities.",
 "rules":     "global tunables, read by name.",
 "sounds":    "synthesised at runtime, no audio files. wave: square|sawtooth|triangle|sine|noise.",
 "prompts":   "the cue above the attack line; one is drawn at random each turn.",
 "loadouts":  "one Loadout per emotion. Slots are positional and a blank slot is a real\n   empty slot in the panel. A Loadout may hold any ability whose emotion set\n   includes its own emotion (see abilities.emotions).",
 "moments":   "title-screen mood line. day is MON..SUN or *; hours are BARCELONA local,\n   to_hour exclusive, and a band may wrap past midnight. Highest priority wins.",
 "status_effects": "one row per status. Abilities apply these by id via status_apply.\n   block_regen = layers held down; miss_chance = attacks the victim fluffs;\n   self_hits = the victim turns one of its own attacks on itself each turn.",
 "dialogue":  "what each enemy says. state: INTRO | WINNING | LOSING | DEFEAT. A battle picks one\n   persona at random from the rows matching the enemy's emotion.",
}

def find(folder, table):
    for p in glob.glob(os.path.join(folder, "*.csv")):
        stem = os.path.splitext(os.path.basename(p))[0]
        name = re.split(r"\s+-\s+", stem)[-1].strip().lower()
        if name == table:
            return p
    return None

def clean(path):
    """Strip the two banner rows the workbook carries (note + LIVE/planned tags),
    drop fully-empty rows, and re-emit tidy CSV."""
    with open(path, newline="", encoding="utf-8-sig") as fh:
        rows = [r for r in csv.reader(fh)]
    rows = [r for r in rows if any(c.strip() for c in r)]
    # the header row is the first one whose first cell is a known key column
    keys = {"id", "key", "attack_emotion", "emotion"}
    start = next((i for i, r in enumerate(rows) if r and r[0].strip() in keys), 0)
    rows = rows[start:]
    if len(rows) > 1 and rows[1] and rows[1][0].strip().upper() in ("LIVE", "PLANNED"):
        del rows[1]
    width = len(rows[0])
    keep = [i for i, h in enumerate(rows[0][:width]) if h.strip() not in DROP_COLUMNS]
    out = []
    for r in rows:
        r = (r + [""] * width)[:width]
        r = [r[i] for i in keep]
        cells = []
        for c in r:
            c = c.replace("\r", " ").replace("\n", " ").strip()
            if "," in c or '"' in c:          # re-quote so the JS reader sees one field
                c = '"' + c.replace('"', '""') + '"'
            cells.append(c)
        out.append(",".join(cells))
    return "\n".join(out)

def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    folder = sys.argv[1]
    blocks, missing = [], []
    for t in TABLES:
        p = find(folder, t)
        if not p:
            missing.append(t); continue
        body = clean(p)
        comment = HEADER_COMMENTS.get(t, "")
        blocks.append(f"/* --- {t} ---\n   {comment}  */\n{t}: `{body}`")
    if missing:
        print("! no CSV found for:", ", ".join(missing))
        print("  (keeping the existing block for those tables is not supported — "
              "export every sheet)")
        sys.exit(1)

    js = r'''/* =====================================================================
   NEURO-METRO: AVUI — DATA TABLES
   GENERATED by tools/build_data.py from the config spreadsheet.
   Edit the spreadsheet, export the sheets as CSV, re-run the script.
   Hand edits here are fine for a quick test but will be overwritten.
   ===================================================================== */

const SCHEMA = {
  bool: ["hits_layer", "enabled"],
  list: ["layers", "pool", "loadouts", "emotions"]
};

const DATA = {

''' + ",\n\n".join(blocks) + r'''
};

/* --- CSV reader: handles quoted fields, so notes may contain commas ---- */
function splitCSVLine(line){
  const out=[]; let cur="", q=false;
  for(let i=0;i<line.length;i++){
    const c=line[i];
    if(q){
      if(c==='"'){ if(line[i+1]==='"'){cur+='"'; i++;} else q=false; }
      else cur+=c;
    }else{
      if(c==='"') q=true;
      else if(c===",") { out.push(cur); cur=""; }
      else cur+=c;
    }
  }
  out.push(cur); return out;
}
function parseCSV(src){
  const lines = src.trim().split(/\r?\n/).filter(l=>l.trim()!=="");
  const head = splitCSVLine(lines.shift()).map(h=>h.trim());
  return lines.map(line=>{
    const cells = splitCSVLine(line);
    const row = {};
    head.forEach((h,i)=>{
      let v = (cells[i]??"").trim();
      if(SCHEMA.list.includes(h))      row[h] = v ? v.split("|").map(s=>s.trim()) : [];
      else if(SCHEMA.bool.includes(h)) row[h] = v==="1"||v.toUpperCase()==="TRUE";
      else if(v!=="" && !isNaN(Number(v))) row[h] = Number(v);
      else row[h] = v;
    });
    return row;
  });
}
const byId = rows => Object.fromEntries(rows.map(r=>[r.id,r]));

const EMOTIONS  = byId(parseCSV(DATA.emotions));
const ABILITIES = byId(parseCSV(DATA.abilities));
const UNITS     = byId(parseCSV(DATA.units));
const RULES     = Object.fromEntries(parseCSV(DATA.rules).map(r=>[r.key,r.value]));
const SOUNDS    = byId(parseCSV(DATA.sounds));
const MATCHUPS  = parseCSV(DATA.matchups);
const DIALOGUE  = parseCSV(DATA.dialogue);
const STATUSES  = byId(parseCSV(DATA.status_effects).filter(r=>r.enabled));
const MOMENTS   = parseCSV(DATA.moments).filter(r=>r.enabled);
const LOADOUTS  = byId(parseCSV(DATA.loadouts).filter(r=>r.enabled));
const PROMPTS   = parseCSV(DATA.prompts).filter(r=>r.enabled);
'''
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(js)
    print("wrote", os.path.relpath(OUT), "-", len(blocks), "tables")

if __name__ == "__main__":
    main()
