/* =====================================================================
   NEURO-METRO: AVUI — DATA TABLES
   GENERATED by tools/build_data.py from the config spreadsheet.
   Edit the spreadsheet, export the sheets as CSV, re-run the script.
   Hand edits here are fine for a quick test but will be overwritten.
   ===================================================================== */

const SCHEMA = {
  bool: ["hits_layer", "enabled"],
  list: ["layers", "pool"]
};

const DATA = {

/* --- emotions ---
   one row per emotion. `token` maps to the CSS palette variable.  */
emotions: `id,name,token,hex,bg_hex,short,description,enabled,notes
ANGER,Anger,anger,#e53859,#2a0810,ANG,"Hot, direct, aggressive.",1,
SURPRISE,Surprise,surprise,#724082,#170a1b,SUR,"Sudden, disruptive, disorienting.",1,
DISGUST,Disgust,disgust,#56a36a,#0c1f13,DIS,"Rejecting, corrosive, contemptuous.",1,
JOY,Joy,joy,#fcc336,#2a1f06,JOY,"Bright, volatile, energising.",1,
SADNESS,Sadness,sadness,#3d66c1,#0a1229,SAD,"Heavy, draining, persistent.",1,
FEAR,Fear,fear,#929fa5,#1a1e20,FEA,"Cold, freezing, evasive.",1,`,

/* --- abilities ---
   kind DAMAGE|SHIELD · power = damage or shield charges · blank emotion = typeless
   (never matches a layer) · hits_layer = whether a hit rotates the target's queue.  */
abilities: `id,name,emotion,cost,kind,power,charge,hits_layer,icon,target,reach,self_ms,self_ec,ec_push_target,ec_drain_target,heal,shield_gain,pierce_shield,ignore_layer,repeat,cooldown,uses,blurb,status_apply,status_chance,status_duration,combo_tag,requires_prev_tag,synergy_group,wild_target,rarity,unlock,enabled,notes
ATK_ANGER,Anger,ANGER,20,DAMAGE,35,0,1,BOLT,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,3,"A straight {ANGER} strike. Costs {EC}, takes {MS} off the target and cracks its outermost {LAYER}.",,0,0,,,,LOWEST_MS,COMMON,,1,
ATK_SADNESS,Sadness,SADNESS,20,DAMAGE,35,0,1,DROP,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,3,"A straight {SADNESS} strike. Costs {EC}, takes {MS} off the target and cracks its outermost {LAYER}.",,0,0,,,,LOWEST_MS,COMMON,,1,
ATK_JOY,Joy,JOY,20,DAMAGE,35,0,1,SPARK,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,3,"A straight {JOY} strike. Costs {EC}, takes {MS} off the target and cracks its outermost {LAYER}.",,0,0,,,,LOWEST_MS,COMMON,,1,
DEFEND,Defend,,10,SHIELD,1,0,0,SHIELD,SELF,SINGLE,0,0,0,0,0,1,0,0,1,1,3,Raises a guard. The next hit against you is *blocked* outright instead of costing {MS}.,,0,0,,,,SELF,COMMON,,1,
HVY_ANGER,Rage,ANGER,45,DAMAGE,90,2,1,BOLT,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,2,"Heavy {ANGER}. Holds two *charge* segments first, so it lands late and hands the opponent room, but it hits for almost triple.",,0,0,,,,LOWEST_MS,COMMON,,1,
HVY_SADNESS,Grief,SADNESS,45,DAMAGE,90,2,1,DROP,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,2,"Heavy {SADNESS}. Holds two *charge* segments first, so it lands late and hands the opponent room, but it hits for almost triple.",,0,0,,,,LOWEST_MS,COMMON,,1,
HVY_JOY,Mania,JOY,60,DAMAGE,130,3,1,SPARK,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,2,"Heavy {JOY}. Three *charge* segments and the hardest hit in the pool. Slow, loud, and expensive in every sense.",,0,0,,,,LOWEST_MS,COMMON,,1,
RECHARGE,Recharge,,0,CHARGE,20,0,0,CHARGE,SELF,SINGLE,5,0,0,0,0,0,0,0,1,1,3,Buys {EC} with your own {MS}. Gains charge and lowers your ceiling at the same time — watch the {OVERLOAD} line.,,0,0,,,,SELF,COMMON,,1,Gains 20 EC and costs 5 of your own MS — which also lowers your ceiling.
GEN_DISGUST,Bile,DISGUST,15,ADDLAYER,1,0,0,ROT,SELF,SINGLE,0,0,0,0,0,0,0,0,1,1,2,"Grows one extra {DISGUST} {LAYER} on yourself. *Grown layers never regrow* — once it breaks, it is gone.",,0,0,,,,SELF,COMMON,,1,Grows one extra Disgust layer. Grown layers are TEMPORARY: once broken they never regrow.
GEN_ANGER,Bristle,ANGER,15,ADDLAYER,1,0,0,ROT,SELF,SINGLE,0,0,0,0,0,0,0,0,1,1,2,"Grows one extra {ANGER} {LAYER} on yourself. *Grown layers never regrow* — once it breaks, it is gone.",,0,0,,,,SELF,COMMON,,1,Grows one extra Anger layer. Grown layers are TEMPORARY: once broken they never regrow.
ROT,Rot,DISGUST,25,DEBUFF,0,0,0,ROT,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,2,{DISGUST} rot. For *2 turns* the target cannot regrow *2* of its broken {LAYERS}.,NO_REGEN,0,2,,,,LOWEST_MS,COMMON,,1,For 2 turns the target cannot regrow 2 of its broken layers.
INFLICT_SAD,Self-Harm,SADNESS,30,DEBUFF,0,0,0,DROP,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,2,{SADNESS} turned inward. For *2 turns* the target uses one of its own attacks *on itself* at the end of every round.,SAD,0,2,,,,LOWEST_MS,COMMON,,1,"Each round end the target turns one of its own attacks on itself. NOTE: distinct from SELF_HARM, which is the Overload-forced station."
BLIND,Blinded by Hate,ANGER,30,DEBUFF,0,0,0,EYE,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,2,{ANGER} blots out aim. For *2 turns* the target *misses half* of its attacks.,BLINDED,0,2,,,,LOWEST_MS,COMMON,,1,ENEMY ability. The target misses half its attacks for 2 turns.
SELF_HARM,Self Harm,,0,SELFHARM,25,0,0,WARN,SELF,SINGLE,0,0,0,0,0,0,0,0,1,0,0,Forced onto your line by {OVERLOAD}. Costs you {MS} and cannot be removed.,,0,0,,,,SELF,OVERLOAD,,1,OVERLOAD ONLY. Forced into your line when Charge passes your ceiling. Cannot be moved or removed.
FEED,Feed,,0,FEED,30,0,0,DROP,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,0,0,Forced onto your line by {OVERLOAD}. *Heals your opponent* and cannot be removed.,,0,0,,,,AS_WRITTEN,OVERLOAD,,1,OVERLOAD ONLY. Heals your opponent. Cannot be moved or removed.`,

/* --- matchups ---
   attack emotion x layer emotion. '*' is a wildcard, 'NONE' means the target has
   no layers. Highest priority wins, so a specific pair always beats a wildcard.
   Adding a synergy is adding a row.  */
matchups: `attack_emotion,layer_emotion,priority,dmg_mult,ec_mult,label,tag_class,sound,rotates_layer,self_ec,status_apply,enabled,notes
*,*,0,1,0,OFF TYPE,off,hit,,0,,1,Fallback. Every pair you do not name lands here.
*,NONE,5,2,0,EXPOSED!,dmg,hit,,0,,1,"No layers left: double damage, no charge."
ANGER,ANGER,10,0.5,1,ABSORBED!,absorb,absorb,,0,,1,Same emotion: the layer drinks it.
SURPRISE,SURPRISE,10,0.5,1,ABSORBED!,absorb,absorb,,0,,1,Same emotion: the layer drinks it.
DISGUST,DISGUST,10,0.5,1,ABSORBED!,absorb,absorb,,0,,1,Same emotion: the layer drinks it.
JOY,JOY,10,0.5,1,ABSORBED!,absorb,absorb,,0,,1,Same emotion: the layer drinks it.
SADNESS,SADNESS,10,0.5,1,ABSORBED!,absorb,absorb,,0,,1,Same emotion: the layer drinks it.
FEAR,FEAR,10,0.5,1,ABSORBED!,absorb,absorb,,0,,1,Same emotion: the layer drinks it.`,

/* --- units ---
   layers are outermost-first and rotate as they take hits. pool = usable abilities.  */
units: `id,name,emotion,max_ms,start_ec_pct,layers,pool,line_dir,line_cap,max_bonus_slots,ai_profile,init,start_shield,max_layers_override,tags,enabled,notes
player,You,,400,0.4,JOY|SADNESS,ATK_ANGER|ATK_SADNESS|ATK_JOY|DEFEND|RECHARGE|HVY_ANGER|HVY_SADNESS|HVY_JOY|GEN_DISGUST|GEN_ANGER|ROT|INFLICT_SAD,1,3,6,,10,0,,PLAYER,1,
enemy,The Commuter,ANGER,250,0.4,ANGER|ANGER|SADNESS,ATK_ANGER|ATK_SADNESS|ATK_JOY|DEFEND|RECHARGE|HVY_ANGER|HVY_SADNESS|HVY_JOY|BLIND,-1,3,6,GREEDY_MAX_DAMAGE,8,0,,ENEMY,1,"AI reads the matchups sheet, so retuning it retunes the AI."`,

/* --- dialogue ---
   what each enemy says. state: INTRO | WINNING | LOSING | DEFEAT. A battle picks one
   persona at random from the rows matching the enemy's emotion.  */
dialogue: `emotion,persona,state,line,enabled,notes
ANGER,The Evicted,INTRO,Thirty years in this flat and they sell it to a fund! I'LL BURN IT DOWN WITH YOU IN IT!,1,
ANGER,The Evicted,WINNING,Choke on the ashes! CHOKE ON THEM!,1,
ANGER,The Evicted,LOSING,No... my things... my life...,1,
ANGER,The Evicted,DEFEAT,Just let me... lock the door... one last time.,1,
ANGER,The Exploited,INTRO,Fourteen hours biking in the rain for three euros! I'LL BREAK YOUR FUCKING LEGS!,1,
ANGER,The Exploited,WINNING,Take your luxury takeout and choke on it!,1,
ANGER,The Exploited,LOSING,My bike... I can't afford to fix my bike...,1,
ANGER,The Exploited,DEFEAT,The app... it says I'm deactivated...,1,
ANGER,The Betrayed,INTRO,You think a text message makes up for six months of lies?! I'LL TEAR YOUR THROAT OUT!,1,
ANGER,The Betrayed,WINNING,Look at me! Look at me when I'm screaming at you!,1,
ANGER,The Betrayed,LOSING,Stop deflecting... stop making me the crazy one!,1,
ANGER,The Betrayed,DEFEAT,I just... wanted the truth.,1,
ANGER,The Vandal,INTRO,This isn't your playground! Get out of my neighborhood before I smash your skull!,1,
ANGER,The Vandal,WINNING,Go back to your perfect little life!,1,
ANGER,The Vandal,LOSING,There are too many of you...,1,
ANGER,The Vandal,DEFEAT,We're being erased...,1,
ANGER,The Denied,INTRO,Three years waiting for papers and you stamp DENIED?! I'LL KILL EVERYONE HERE!,1,
ANGER,The Denied,WINNING,Stamp this! STAMP THIS IN BLOOD!,1,
ANGER,The Denied,LOSING,"Please, you don't understand what they'll do to me...",1,
ANGER,The Denied,DEFEAT,I don't exist anymore...,1,
DISGUST,The Aristocrat,INTRO,"Look at you, sweating on the metro. Did you even shower before touching my city?",1,
DISGUST,The Aristocrat,WINNING,Filth always sinks to the bottom. Stay there.,1,
DISGUST,The Aristocrat,LOSING,Don't touch me with those calloused hands!,1,
DISGUST,The Aristocrat,DEFEAT,Your smell... it won't wash off...,1,
DISGUST,The Apathetic,INTRO,Another addict blocking the ATM. Can't you just die somewhere out of sight?,1,
DISGUST,The Apathetic,WINNING,Scrape yourself off my shoes.,1,
DISGUST,The Apathetic,LOSING,Don't bleed on my designer coat!,1,
DISGUST,The Apathetic,DEFEAT,I am... better than this...,1,
DISGUST,The Xenophobe,INTRO,"You come here, take our space, speak your garbage language. You make me sick.",1,
DISGUST,The Xenophobe,WINNING,Clean it up. That's all you're good for.,1,
DISGUST,The Xenophobe,LOSING,How dare you speak back to me?!,1,
DISGUST,The Xenophobe,DEFEAT,This isn't... your home...,1,
DISGUST,The Purist,INTRO,"Plastic faces, fake lips, empty heads. You're a walking infection in this club.",1,
DISGUST,The Purist,WINNING,Choke on your vanity.,1,
DISGUST,The Purist,LOSING,Get your cheap perfume away from me.,1,
DISGUST,The Purist,DEFEAT,It's all so... hollow...,1,
DISGUST,The Mirror,INTRO,"I see the track marks under your sleeves. You're rotting from the inside, just like me.",1,
DISGUST,The Mirror,WINNING,We belong in the gutter. Accept it.,1,
DISGUST,The Mirror,LOSING,Don't look at me with pity!,1,
DISGUST,The Mirror,DEFEAT,Just... one more hit to make it stop...,1,
SADNESS,The Left Behind,INTRO,No. Dad didn't leave. Dad loves me... Loved me?,1,
SADNESS,The Left Behind,WINNING,I'll make you stay! Nobody leaves me again!,1,
SADNESS,The Left Behind,LOSING,Did I do something wrong?,1,
SADNESS,The Left Behind,DEFEAT,I'll be good... I promise I'll be good...,1,
SADNESS,The Isolated,INTRO,The hospital called. Nobody came to claim his things. Am I next?,1,
SADNESS,The Isolated,WINNING,If you stay down... it hurts less. I promise.,1,
SADNESS,The Isolated,LOSING,Why does everyone walk away?,1,
SADNESS,The Isolated,DEFEAT,Finally... it's quiet.,1,
SADNESS,The Erased,INTRO,My grandfather built this bar. Now it's a fucking brunch spot... I have nothing.,1,
SADNESS,The Erased,WINNING,Drink the bitterness. It's all we have left.,1,
SADNESS,The Erased,LOSING,They're painting over the mural...,1,
SADNESS,The Erased,DEFEAT,I don't recognize my own street.,1,
SADNESS,The Grieving,INTRO,The sea was supposed to be calm... they promised it was safe to cross...,1,
SADNESS,The Grieving,WINNING,Drown with me! Drown with my memories!,1,
SADNESS,The Grieving,LOSING,I can't hold on to the raft...,1,
SADNESS,The Grieving,DEFEAT,The water is so cold...,1,
SADNESS,The Broken Dream,INTRO,Ten years playing in the metro... nobody even looks up anymore.,1,
SADNESS,The Broken Dream,WINNING,LISTEN TO ME! FOR ONCE IN YOUR LIFE!,1,
SADNESS,The Broken Dream,LOSING,My strings are snapping...,1,
SADNESS,The Broken Dream,DEFEAT,Silence... just like always.,1,
FEAR,The Hunted,INTRO,"Shhhh shhhhhhhhh! Those transphobes behind the corner, they'll notice us, move back slowly... oh no OH NO",1,
FEAR,The Hunted,WINNING,STAY BACK! I HAVE A KNIFE!,1,
FEAR,The Hunted,LOSING,"Please, I just want to walk home...",1,
FEAR,The Hunted,DEFEAT,Not again... please not again...,1,
FEAR,The Paranoid,INTRO,The cameras on the streetlights—they track our heartbeats. Don't let them see you panic!,1,
FEAR,The Paranoid,WINNING,I'll blind them! I'LL BLIND THE WHOLE CITY!,1,
FEAR,The Paranoid,LOSING,They're zooming in... they know my name...,1,
FEAR,The Paranoid,DEFEAT,Erase my... search history...,1,
FEAR,The Debt-Ridden,INTRO,"I have the money, I swear! Just give me till Friday!",1,
FEAR,The Debt-Ridden,WINNING,I'll take yours! I'll pay them with your blood!,1,
FEAR,The Debt-Ridden,LOSING,They're going to break my hands...,1,
FEAR,The Debt-Ridden,DEFEAT,Tell my mother... I'm sorry...,1,
FEAR,The Trapped,INTRO,He said he wouldn't hit me again if I just stayed quiet...,1,
FEAR,The Trapped,WINNING,Don't make him angry! Just do what he says!,1,
FEAR,The Trapped,LOSING,He's coming up the stairs... I can hear his keys...,1,
FEAR,The Trapped,DEFEAT,It was always going to end like this...,1,
FEAR,The Night-Walker,INTRO,Footsteps. Stop. Footsteps. Why are they matching my pace?,1,
FEAR,The Night-Walker,WINNING,I'll run! You can't catch me in the dark!,1,
FEAR,The Night-Walker,LOSING,The streetlights are all broken here...,1,
FEAR,The Night-Walker,DEFEAT,Nobody can hear me scream...,1,
JOY,The Delusional,INTRO,Life is MINE and this street is MY world to strut by and BLIND YOU WITH MY LIGHT,1,
JOY,The Delusional,WINNING,Bask in my glory! I am untouched by sorrow!,1,
JOY,The Delusional,LOSING,Wait... why is everyone looking at me like that?,1,
JOY,The Delusional,DEFEAT,The spotlight... it's fading...,1,
JOY,The Substance Abuser,INTRO,"Another pill, another party! The sun never sets in Raval if your eyes are wide enough!",1,
JOY,The Substance Abuser,WINNING,DANCE WITH ME! WHY AREN'T YOU DANCING?!,1,
JOY,The Substance Abuser,LOSING,"No, no, the comedown... I can't feel my teeth...",1,
JOY,The Substance Abuser,DEFEAT,It's so dark... where did the music go?,1,
JOY,The Cultist,INTRO,We are all just vibrations! I have transcended this fleshy prison!,1,
JOY,The Cultist,WINNING,Let me cleanse your aura... WITH FIRE!,1,
JOY,The Cultist,LOSING,My chakras... they are bleeding...,1,
JOY,The Cultist,DEFEAT,The universe... lied to me...,1,
JOY,The Influencer,INTRO,"A million followers, baby! Look at this view, look at this life!",1,
JOY,The Influencer,WINNING,"SMILE FOR THE CAMERA, TRASH!",1,
JOY,The Influencer,LOSING,I'm losing sponsors... I'm losing relevance...,1,
JOY,The Influencer,DEFEAT,Did anybody... even like... the post?,1,
JOY,The Pyromaniac,INTRO,Look at how pretty the flames are on the dumpsters! It's art!,1,
JOY,The Pyromaniac,WINNING,BURN! EVERYTHING LOOKS BETTER IN RED!,1,
JOY,The Pyromaniac,LOSING,The smoke... I can't breathe...,1,
JOY,The Pyromaniac,DEFEAT,"Just embers... cold, dead embers...",1,
SURPRISE,The Betrayed,INTRO,"Yesss YESSSS give me that sweet sweet nectar GIVE IT... wait, what did you just inject me with?",1,
SURPRISE,The Betrayed,WINNING,I'LL TEAR THE POISON OUT OF YOUR CHEST!,1,
SURPRISE,The Betrayed,LOSING,My heart... it's beating too fast...,1,
SURPRISE,The Betrayed,DEFEAT,You... you killed me...,1,
SURPRISE,The Accident,INTRO,The light was green! I swear on my mother's life the light was green!,1,
SURPRISE,The Accident,WINNING,"You see it too, right? The glass in my hair?",1,
SURPRISE,The Accident,LOSING,Why is the steering wheel bending like that?,1,
SURPRISE,The Accident,DEFEAT,I can't... feel my legs...,1,
SURPRISE,The Diagnosis,INTRO,"Six months? You're joking, right? I ran a marathon yesterday...",1,
SURPRISE,The Diagnosis,WINNING,I'M NOT SICK! LOOK AT HOW STRONG I AM!,1,
SURPRISE,The Diagnosis,LOSING,Why am I coughing blood...?,1,
SURPRISE,The Diagnosis,DEFEAT,I don't have enough time...,1,
SURPRISE,The Raid,INTRO,"They're breaking down the door! Throw it in the toilet, NOW!",1,
SURPRISE,The Raid,WINNING,"YOU'LL NEVER TAKE ME ALIVE, PIGS!",1,
SURPRISE,The Raid,LOSING,The window... it's too high up...,1,
SURPRISE,The Raid,DEFEAT,Handcuffs... so cold...,1,
SURPRISE,The Ghost,INTRO,Why won't anybody look at me? I've been screaming on this platform for hours...,1,
SURPRISE,The Ghost,WINNING,FEEL ME! FEEL MY COLD HANDS!,1,
SURPRISE,The Ghost,LOSING,My reflection... I don't have a reflection...,1,
SURPRISE,The Ghost,DEFEAT,I died... I died under the metro...,1,`,

/* --- rules ---
   global tunables, read by name.  */
rules: `key,value,description,,,
lineCap,3,"FALLBACK line size, used only if a unit row leaves line_cap blank.",,,
maxLayers,6,Layer slots per unit.,,,
restEc,15,Charge gained by departing with an empty line.,,,
ecBasis,POWER,POWER = charge figured from the ability's base power. DEALT = from damage actually dealt.,,,
noLayerDmgMult,1,Superseded by the matchups sheet; kept as a fallback.,,,
noLayerEcMult,0,Superseded by the matchups sheet; kept as a fallback.,,,
shieldRotatesLayer,0,Whether a blocked attack still rotates the layer queue.,,,
lowMsWarnPct,0.18,Below this fraction of max MS the ceiling chevron pulses red.,,,
clashSeconds,4,Length of the death sequence.,,,
layerRegenAtTurnEnd,1,"Broken layers stay gone until the round ends, then regrow at the back of the queue.",,,
chargeStepMs,260,How long each charge segment holds before the next.,,,
flyMs,420,How long a station takes to fly across and strike the target.,,,
typeMs,32,Delay between letters of dialogue.,,,
dialogueHoldMs,3000,How long a finished line stays on screen before it fades.,,,
lowHpTalkPct,0.2,Fraction of max MS below which the winning / losing lines fire.,,,
overloadSlotPer,0.25,Every this-much overflow (as a fraction of max MS) forces one more corrupted slot.,,,
aiVarietyChance,0.22,Chance the AI takes a random affordable attack instead of its best one.,,,
aiDebuffChance,0.5,Chance the AI spends a slot on a debuff the target is not already suffering.,,,
aiChargeBias,0.55,Chance the AI prefers an ability with charge segments when it can afford one.,,,
shuffleLayersEachRound,1,Re-order every unit's layer queue at the start of each round.,,,
chargeGrantsSlots,1,Each charge segment in a line grants the OPPONENT one temporary slot next turn.,,,
maxBonusSlots,6,"FALLBACK cap on temporary slots, used only if a unit row leaves max_bonus_slots blank.",,,
abilPageSize,4,Abilities shown per page in the Emotions panel.,,,
slotArriveMs,260,Gap between one temporary slot flying in and the next.,,,
unsheathMs,340,How long one interface element takes to draw itself into place.,,,
unsheathGapMs,110,"Gap before the next element starts — smaller than unsheathMs, so they overlap.",,,
longPressMs,420,How long an ability must be held before its tooltip opens.,,,
swipeMinPx,36,How far a pointer must travel across the panel to count as a page swipe.,,,
tagGrowth,0.85,How much an accumulating tag grows once it holds a full max-MS worth of change.,,,
tagBreathSlowMs,1700,Breathing period of an accumulating tag holding almost nothing.,,,
tagBreathFastMs,380,Breathing period of a tag holding a full max-MS worth — it flashes far harder.,,,
gaugeW,134,"Gauge canvas width in logical pixels. Lower = chunkier pixels, coarser value steps.",,,
gaugeH,22,Gauge canvas height in logical pixels — tall enough for the end caps.,,,
barCoreH,12,"Height of the bar's interior, before the wave, in logical pixels.",,,
barWaveAmp,1.4,Wave amplitude on the bar's silhouette (reference: 9.8 of a 1026-long bar).,,,
barWaveHalf,5.6,"Half-period of the silhouette wave, i.e. one arc (reference: 43.3).",,,
barWaveSpeed,0.1,How fast the silhouette wave travels.,,,
ecBandFrac,0.82,Charge fill height as a fraction of the bar interior (reference: 76 of 92.74).,,,
ecWaveAmp,0.7,"Amplitude of the charge fill's own wave — long and shallow, per the reference.",,,
ecWaveHalf,19,Half-period of the charge fill's wave. Much longer than the silhouette's.,,,
ecWaveSpeed,0.05,How fast the charge wave travels.,,,
ecInnerFrac,0.5,"Inner charge bar thickness, as a fraction of the outer one. Same shape, dodged over it.",,,
ecInnerAmt,0.4,How hard the inner charge bar dodges. 1 blows out to white; lower keeps the hue.,,,
arcSpacing,3.1,Spacing of the background arc texture (reference: 23.83).,,,
arcRadius,12.6,Radius of the background arcs (reference: 96.95).,,,
arcAlpha,0.11,How strongly the arcs show. They only read against the unlit stretch.,,,
capW,5,End-cap width in logical pixels.,,,
capR,2,End-cap corner rounding in logical pixels.,,,
ballFlyMs,330,How long a ball of light takes to arc from its indicator into the bar.,,,
settleStepMs,70,Pause between one hit landing on a bar and the next setting off.,,,
barTweenMs,1000,How long a bar takes to travel to its new value once a hit lands.,,,
overloadHoldMs,2000,How long the OVERLOAD tag and its slow motion last.,,,
ecScrollSpeed,0.0022,How fast the charge gradient drifts along the bar.,,,
themeOpening,audio/theme-opening.wav,Theme part 1: plays once.,,,
themeLoop,audio/theme-loop.wav,"Theme part 2: loops for ever, scheduled to start the instant part 1 ends.",,,
musicFadeMs,900,How quickly the theme fades out when the battle ends.,,,
musicVolume,0.3,Theme level. Lower this if the sound effects are getting buried.,,,
sfxVolume,1.05,"Sound-effect level, mixed against musicVolume.",,,
layerEase,0.16,How fast layers slide to their new slot. Higher = snappier.,,,
layerWaveDelay,0.85,"Phase offset per slot, so breathing travels outward in waves.",,,
layerInnerShrink,0.85,Curve of the radius falloff toward the centre.,,,
layerFill,0.42,Ring thickness as a fraction of the gap to the next slot.,,,
layerOuterThick,2,Thickness multiplier for the outermost (active) layer.,,,
layerInnerThick,0.9,Thickness multiplier for every layer behind it.,,,
layerFlashMs,240,How long a struck layer flashes white before vanishing.,,,
layerGapMs,260,Beat between the layer vanishing and it regrowing at the back.,,,
layerRegrowMs,380,How long the regrow beat holds before resolution continues.,,,
enemyRingBaseR,28,"Enemy: radius of the outermost ring, in logical canvas pixels.",,,
enemyRingSpacing,4.7,Enemy: radius step between one layer and the next in. baseR/spacing sets how many fit.,,,
enemyRingBreathe,1.6,Enemy ring breathing amplitude.,,,
playerRingBaseR,300,Player: radius of the outermost ring. Huge on purpose — a big circle reads as a nearly flat band.,,,
playerRingSpacing,5,"Player: radius step between layers. Small, so all six sit in a thin arc despite the huge radius.",,,
playerRingBreathe,2.2,Player ring breathing amplitude.,,,
playerCanvasW,120,Player ring canvas width in logical pixels (wide and short).,,,
playerCanvasH,32,Player ring canvas height in logical pixels.,,,
playerRingCy,300,"Player: circle centre Y, pushed far below the strip so only the flat top of the arc shows.",,,
crusherSteps,12,"Audio bit-crusher quantisation. Low = Atari harsh, high = SNES-clean.",,,`,

/* --- sounds ---
   synthesised at runtime, no audio files. wave: square|sawtooth|triangle|sine|noise.  */
sounds: `id,wave,f0,f1,dur,gain,echo,description
tap,square,980,1460,80,0.46,0.3,Adding an ability to the line.
place,square,620,1760,130,0.4,0.35,The station lands on your line and flashes white.
sheatheE,sawtooth,1500,220,150,0.3,0.22,Enemy UI element drawn into place. Lower.
sheatheP,sawtooth,2100,340,140,0.28,0.22,Player UI element drawn into place. Higher.
slot,triangle,300,1500,150,0.3,0.45,A temporary slot flies in from the opponent.
remove,square,520,220,90,0.34,0.24,Removing a station.
depart,sawtooth,240,70,420,0.26,0.45,The line departs and charge is spent.
travel,square,150,150,38,0.1,0.15,Line scrolling to the next station.
arrive,square,880,880,45,0.14,0.3,Station reaches the head and lights up.
hit,noise,700,700,190,0.34,0.4,Off-type hit.
absorb,square,300,1200,260,0.24,0.5,Same-type hit: the layer absorbs it.
block,noise,1600,1600,90,0.3,0.35,"Shield blocks, or shield goes up."
breaklayer,sawtooth,760,80,340,0.28,0.55,A layer flashes and breaks.
regrow,triangle,120,520,300,0.16,0.4,The broken layer regrows at the back.
clash,noise,240,240,1500,0.4,0.65,Death: the chevrons meet.
speak,square,620,540,42,0.09,0.12,One letter of dialogue appearing.
win,square,440,1320,620,0.24,0.55,Victory.
lose,sawtooth,320,50,950,0.28,0.6,Defeat.`,

/* --- status_effects ---
   one row per status. Abilities apply these by id via status_apply.
   block_regen = layers held down; miss_chance = attacks the victim fluffs;
   self_hits = the victim turns one of its own attacks on itself each turn.  */
status_effects: `id,name,duration,icon,color,blurb,block_regen,miss_chance,self_hits,dmg_taken_mult,dmg_dealt_mult,ec_gain_mult,ms_per_turn,ec_per_turn,blocks_actions,stacking,max_stacks,enabled,notes
NO_REGEN,Rotting,2,ROT,#56a36a,*2* of your broken {LAYERS} are being held down. They stay broken until this wears off.,2,0,0,1,1,1,0,0,0,REFRESH,1,1,Holds this many broken layers down: they stay broken while it lasts.
SAD,Sad,2,DROP,#3d66c1,At the end of every round one of your own attacks is turned *on yourself*.,0,0,1,1,1,1,0,0,0,REFRESH,1,1,Each round end the victim turns one of its OWN attacks on itself.
BLINDED,Blinded,2,EYE,#e53859,{ANGER} has blotted out your aim. *Half* of your attacks miss outright.,0,0.5,0,1,1,1,0,0,0,REFRESH,1,1,The victim fluffs this fraction of its attacks.`,

/* --- moments ---
   title-screen mood line. day is MON..SUN or *; hours are BARCELONA local,
   to_hour exclusive, and a band may wrap past midnight. Highest priority wins.  */
moments: `id,day,from_hour,to_hour,phrase,priority,enabled,notes
dawn_1,*,5,7,the first light is still deciding,0,1,
dawn_2,*,5,7,nobody has spoken yet today,0,1,
morn_1,*,7,10,early morning,0,1,
morn_2,*,7,10,the early carriages are full of unfinished sleep,0,1,
morn_3,*,7,10,everyone is already late,0,1,
mid_1,*,10,13,middle of the day,0,1,
mid_2,*,10,13,the light is flat and honest,0,1,
noon_1,*,13,16,all afternoon ahead,0,1,
noon_2,*,13,16,the long slow part of the day,0,1,
late_1,*,16,19,the afternoon is running out,0,1,
late_2,*,16,19,everyone is going somewhere they did not choose,0,1,
dusk_1,*,19,21,somber twilight,0,1,
dusk_2,*,19,21,the hour the day admits what it was,0,1,
night_1,*,21,24,the night is getting loud,0,1,
night_2,*,21,24,the last trains are filling up,0,1,
small_1,*,0,5,"the madrugada, and still moving",0,1,
small_2,*,0,5,too late to be anything but honest,0,1,
mon_morn,MON,5,10,"monday, and the week already weighs something",2,1,
mon_dusk,MON,19,24,the longest monday of the month,2,1,
wed_mid,WED,10,16,the week is stuck exactly in the middle,2,1,
thu_late,THU,16,21,"almost, but not yet",2,1,
fri_dusk,FRI,19,21,a night to finally be free,2,1,
fri_night,FRI,21,24,a night to finally be free,2,1,
fri_small,FRI,0,5,friday refusing to end,2,1,
sat_mid,SAT,10,16,a saturday with nothing owed to anyone,2,1,
sat_night,SAT,21,24,the city is pretending it never has to work again,2,1,
sun_mid,SUN,10,16,a sunday that stretches too far,2,1,
sun_dusk,SUN,19,24,"sunday dusk, and monday already breathing on it",2,1,`
};

/* --- CSV reader: handles quoted fields, so notes may contain commas ---- */
function splitCSVLine(line){
  const out=[]; let cur="", q=false;
  for(let i=0;i<line.length;i++){
    const c=line[i];
    if(q){
      if(c==='"'){ if(line[i+1]==='"'){cur+='"'; i++;} else q=false; }
      else cur+=c;
    }else{
      if(c==='"') q=true;
      else if(c===",") { out.push(cur); cur=""; }
      else cur+=c;
    }
  }
  out.push(cur); return out;
}
function parseCSV(src){
  const lines = src.trim().split(/\r?\n/).filter(l=>l.trim()!=="");
  const head = splitCSVLine(lines.shift()).map(h=>h.trim());
  return lines.map(line=>{
    const cells = splitCSVLine(line);
    const row = {};
    head.forEach((h,i)=>{
      let v = (cells[i]??"").trim();
      if(SCHEMA.list.includes(h))      row[h] = v ? v.split("|").map(s=>s.trim()) : [];
      else if(SCHEMA.bool.includes(h)) row[h] = v==="1"||v.toUpperCase()==="TRUE";
      else if(v!=="" && !isNaN(Number(v))) row[h] = Number(v);
      else row[h] = v;
    });
    return row;
  });
}
const byId = rows => Object.fromEntries(rows.map(r=>[r.id,r]));

const EMOTIONS  = byId(parseCSV(DATA.emotions));
const ABILITIES = byId(parseCSV(DATA.abilities));
const UNITS     = byId(parseCSV(DATA.units));
const RULES     = Object.fromEntries(parseCSV(DATA.rules).map(r=>[r.key,r.value]));
const SOUNDS    = byId(parseCSV(DATA.sounds));
const MATCHUPS  = parseCSV(DATA.matchups);
const DIALOGUE  = parseCSV(DATA.dialogue);
const STATUSES  = byId(parseCSV(DATA.status_effects).filter(r=>r.enabled));
const MOMENTS   = parseCSV(DATA.moments).filter(r=>r.enabled);
