#!/usr/bin/env python3
"""
Write build.js — the version and the moment the project was last touched.

    python3 tools/stamp.py

Run it LAST, right before packaging. It scans the real source files for the newest
modification time rather than trusting its own run time, so the stamp on the title
screen says when the game actually changed, not when this script happened to run.

Version comes from the newest "## Pass NN" heading in README.md, so bumping it is
not a thing anyone has to remember.
"""
import os, re, sys, time
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _paths import app_root

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = app_root()
WATCH_DIRS  = ["src", "styles"]
WATCH_FILES = ["index.html", "data.js", "music.js"]
SKIP = {"build.js"}

def newest():
    best = 0.0
    for d in WATCH_DIRS:
        p = os.path.join(ROOT, d)
        if not os.path.isdir(p): continue
        for f in os.listdir(p):
            if f in SKIP: continue
            fp = os.path.join(p, f)
            if os.path.isfile(fp): best = max(best, os.path.getmtime(fp))
    for f in WATCH_FILES:
        fp = os.path.join(ROOT, f)
        if os.path.isfile(fp): best = max(best, os.path.getmtime(fp))
    return best or time.time()

def version():
    """The newest "## Pass NN" heading there is.

    IT LOOKS IN CHANGELOG.md FIRST. The pass history used to live in README.md and
    was split out of it, and this went on reading the README — which no longer has
    a single Pass heading in it, so the title screen quietly froze at the last
    version the README happened to mention. A version stamp that stops moving is
    worse than none: it says the build is old when it is not."""
    for name in ("CHANGELOG.md", "README.md"):
        try:
            txt = open(os.path.join(ROOT, name), encoding="utf-8").read()
            passes = [int(n) for n in re.findall(r"^## Pass (\d+)", txt, re.M)]
            if passes: return "0.%d" % max(passes)
        except Exception:
            pass
    return "0.0"

def main():
    t = newest()
    stamp = time.strftime("%d %b %Y  %H:%M", time.localtime(t))
    out = ("/* GENERATED by tools/stamp.py — do not edit.\n"
           "   `modified` is the newest mtime across src/, styles/ and the generated\n"
           "   tables, so the title screen reports when the GAME changed. */\n"
           'const BUILD = { version: "v%s", modified: "%s" };\n' % (version(), stamp))
    with open(os.path.join(ROOT, "build.js"), "w", encoding="utf-8") as f:
        f.write(out)
    print("build.js -> v%s  %s" % (version(), stamp))

if __name__ == "__main__":
    main()
