/* =====================================================================
   NEURO-METRO: AVUI — DATA TABLES
   GENERATED by tools/build_data.py from the config spreadsheet.
   Edit the spreadsheet, export the sheets as CSV, re-run the script.
   Hand edits here are fine for a quick test but will be overwritten.
   ===================================================================== */

const SCHEMA = {
  bool: ["hits_layer", "enabled"],
  list: ["layers", "pool", "loadouts", "emotions", "lines", "stations", "spawn",
        "day", "weather", "keys"]
};

const DATA = {

/* --- emotions ---
   one row per emotion. `token` maps to the CSS palette variable.  */
emotions: `id,name,token,hex,bg_hex,short,icon,sfx,description,enabled,notes
ANGER,Anger,anger,#e53859,#2a0810,ANG,BOLT,hit_anger,"Hot, direct, aggressive.",1,
SURPRISE,Surprise,surprise,#724082,#170a1b,SUR,BURST,hit_surprise,"Sudden, disruptive, disorienting.",1,
DISGUST,Disgust,disgust,#56a36a,#0c1f13,DIS,ROT,hit_disgust,"Rejecting, corrosive, contemptuous.",1,
JOY,Joy,joy,#fcc336,#2a1f06,JOY,SPARK,hit_joy,"Bright, volatile, energising.",1,
SADNESS,Sadness,sadness,#3d66c1,#0a1229,SAD,DROP,hit_sadness,"Heavy, draining, persistent.",1,
FEAR,Fear,fear,#929fa5,#1a1e20,FEA,EYE,hit_fear,"Cold, freezing, evasive.",1,`,

/* --- rules ---
   global tunables, read by name.  */
rules: `key,value,description,,,
lineCap,3,"FALLBACK line size, used only if a unit row leaves line_cap blank.",,,
maxLayers,6,Layer slots per unit.,,,
restEc,15,Charge gained by departing with an empty line.,,,
ecBasis,POWER,POWER = charge figured from the ability's base power. DEALT = from damage actually dealt.,,,
noLayerDmgMult,1,Superseded by the matchups sheet; kept as a fallback.,,,
noLayerEcMult,0,Superseded by the matchups sheet; kept as a fallback.,,,
shieldRotatesLayer,0,Whether a blocked attack still rotates the layer queue.,,,
lowMsWarnPct,0.18,Below this fraction of max MS the ceiling chevron pulses red.,,,
clashSeconds,4,Length of the death sequence.,,,
layerRegenAtTurnEnd,1,"Broken layers stay gone until the round ends, then regrow at the back of the queue.",,,
chargeStepMs,260,How long each charge segment holds before the next.,,,
flyMs,120,How long a station takes to fly across and strike the target.,,,
typeMs,32,Delay between letters of dialogue.,,,
dialogueHoldMs,3000,How long a finished line stays on screen before it fades.,,,
lowHpTalkPct,0.2,Fraction of max MS below which the winning / losing lines fire.,,,
overloadSlotPer,0.25,Every this-much overflow (as a fraction of max MS) forces one more corrupted slot.,,,
aiVarietyChance,0.22,Chance the AI takes a random affordable attack instead of its best one.,,,
aiDebuffChance,0.5,Chance the AI spends a slot on a debuff the target is not already suffering.,,,
aiChargeBias,0.55,Chance the AI prefers an ability with charge segments when it can afford one.,,,
shuffleLayersEachRound,1,Re-order every unit's layer queue at the start of each round.,,,
maxExtraSlots,6,Hard cap on extra slots of any kind a line may carry.,,,
loadoutPatternAlpha,0.13,How faint the emotion glyph tiled behind a Loadout button is.,,,
loadoutSlots,4,"Ability slots in one Loadout, and so cells per page.",,,
equippedSlots,3,Loadouts the player carries into a battle.,,,
slotArriveMs,260,Gap between one temporary slot flying in and the next.,,,
impactFlashMs,45,White frame on a hit.,,,
impactShakeMs,85,Shake after that white frame.,,,
stunTurns,1,Turns a unit is stunned for once its last layer breaks. It skips its line and regrows nothing.,,,
lineTravelMs,200,How long the line takes to slide the next station to the centre.,,,
lineFlashMs,90,How long a centred station flashes before it strikes.,,,
chargeShownMax,2,Most charge stations drawn in an ability box; beyond this it just repeats.,,,
critChance,0.05,"Default chance an attack crits, when the ability does not say otherwise.",,,
frameMaxW,420,The phone frame's widest; nothing drawn for it may exceed this.,,,
momentPx,2,Upscale of the title screen's mood line: bigger = chunkier pixels.,,,
momentSize,10,LOGICAL type size; what you see is this times momentPx.,,,
critTagMs,700,How long a plain positioned tag stays up.,,,
critHoldMs,1000,How long CRITICAL is held before the earned slot flies in.,,,
critFlashMs,260,One wash of the screen in the attacking emotion's colour.,,,
critSlotFlyMs,520,The earned slot travelling from the tag to the line.,,,
critMult,2,Damage multiplier on a critical.,,,
statusStepMs,2000,"A station that applies a status holds this long, so it can be read.",,,
attackStepMs,600,"Total time one executed station takes, start to finish.",,,
lineAlertFlashes,3,How many times a line flashes white before it starts executing.,,,
lineAlertMs,110,Length of one of those flashes.,,,
unsheathMs,340,How long one interface element takes to draw itself into place.,,,
unsheathGapMs,110,"Gap before the next element starts — smaller than unsheathMs, so they overlap.",,,
longPressMs,420,How long an ability must be held before its tooltip opens.,,,
swipeMinPx,36,How far a pointer must travel across the panel to count as a page swipe.,,,
tagGrowth,0.85,How much an accumulating tag grows once it holds a full max-MS worth of change.,,,
tagBreathSlowMs,1700,Breathing period of an accumulating tag holding almost nothing.,,,
tagBreathFastMs,380,Breathing period of a tag holding a full max-MS worth — it flashes far harder.,,,
gaugeW,134,"Gauge canvas width in logical pixels. Lower = chunkier pixels, coarser value steps.",,,
gaugeH,22,Gauge canvas height in logical pixels — tall enough for the end caps.,,,
barCoreH,12,"Height of the bar's interior, before the wave, in logical pixels.",,,
barWaveAmp,1.4,Wave amplitude on the bar's silhouette (reference: 9.8 of a 1026-long bar).,,,
barWaveHalf,5.6,"Half-period of the silhouette wave, i.e. one arc (reference: 43.3).",,,
barWaveSpeed,0.1,How fast the silhouette wave travels.,,,
ecBandFrac,0.82,Charge fill height as a fraction of the bar interior (reference: 76 of 92.74).,,,
ecWaveAmp,0.7,"Amplitude of the charge fill's own wave — long and shallow, per the reference.",,,
ecWaveHalf,19,Half-period of the charge fill's wave. Much longer than the silhouette's.,,,
ecWaveSpeed,0.05,How fast the charge wave travels.,,,
ecInnerFrac,0.5,"Inner charge bar thickness, as a fraction of the outer one. Same shape, dodged over it.",,,
ecInnerAmt,0.4,How hard the inner charge bar dodges. 1 blows out to white; lower keeps the hue.,,,
arcSpacing,3.1,Spacing of the background arc texture (reference: 23.83).,,,
arcRadius,12.6,Radius of the background arcs (reference: 96.95).,,,
arcAlpha,0.11,How strongly the arcs show. They only read against the unlit stretch.,,,
capW,5,End-cap width in logical pixels.,,,
capR,2,End-cap corner rounding in logical pixels.,,,
ballFlyMs,330,How long a ball of light takes to arc from its indicator into the bar.,,,
settleStepMs,70,Pause between one hit landing on a bar and the next setting off.,,,
fnumMinPx,20,Smallest a floating damage number gets.,,,
fnumMaxPx,62,Largest — reached when one hit costs a whole stamina bar.,,,
fnumRisePx,34,How far a floating number travels up before it settles.,,,
fnumInMs,600,Fade in while rising.,,,
fnumHoldMs,600,Easing to a stop.,,,
fnumOutMs,400,Fade out.,,,
fnumLingerMs,300,Extra time a floating number holds before it goes.,,,
hitShards,3,Shapes thrown off where an attack lands.,,,
hitShardMs,260,How long one of those shapes flashes.,,,
actionLineMs,620,Buff / debuff streaks over the target.,,,
statusFxMs,1000,Distortion and bloom when a status takes hold.,,,
backdropGlow,0.55,How strongly the enemy's emotion tints the battle backdrop.,,,
barTweenMs,1000,How long a bar takes to travel to its new value once a hit lands.,,,
overloadHoldMs,2000,How long the OVERLOAD tag and its slow motion last.,,,
ecScrollSpeed,0.0044,How fast the charge gradient drifts along the bar.,,,
themeOpening,audio/theme-opening.wav,Theme part 1: plays once.,,,
themeLoop,audio/theme-loop.wav,"Theme part 2: loops for ever, scheduled to start the instant part 1 ends.",,,
musicFadeMs,900,How quickly the theme fades out when the battle ends.,,,
musicVolume,0.3,Theme level. Lower this if the sound effects are getting buried.,,,
sfxVolume,1.05,"Sound-effect level, mixed against musicVolume.",,,
layerEase,0.16,How fast layers slide to their new slot. Higher = snappier.,,,
layerWaveDelay,0.85,"Phase offset per slot, so breathing travels outward in waves.",,,
layerInnerShrink,0.85,Curve of the radius falloff toward the centre.,,,
layerFill,0.42,Ring thickness as a fraction of the gap to the next slot.,,,
layerOuterThick,2,Thickness multiplier for the outermost (active) layer.,,,
layerInnerThick,0.9,Thickness multiplier for every layer behind it.,,,
layerFlashMs,50,How long a struck layer flashes white before vanishing.,,,
layerGapMs,18,Beat between the layer vanishing and it regrowing at the back.,,,
layerRegrowMs,380,How long the regrow beat holds before resolution continues.,,,
enemyRingBaseR,28,"Enemy: radius of the outermost ring, in logical canvas pixels.",,,
enemyRingSpacing,4.7,Enemy: radius step between one layer and the next in. baseR/spacing sets how many fit.,,,
enemyRingBreathe,1.6,Enemy ring breathing amplitude.,,,
playerRingBaseR,300,Player: radius of the outermost ring. Huge on purpose — a big circle reads as a nearly flat band.,,,
playerRingSpacing,5,"Player: radius step between layers. Small, so all six sit in a thin arc despite the huge radius.",,,
playerRingBreathe,2.2,Player ring breathing amplitude.,,,
playerCanvasW,120,Player ring canvas width in logical pixels (wide and short).,,,
playerCanvasH,32,Player ring canvas height in logical pixels.,,,
playerRingCy,300,"Player: circle centre Y, pushed far below the strip so only the flat top of the arc shows.",,,
crusherSteps,12,"Audio bit-crusher quantisation. Low = Atari harsh, high = SNES-clean.",,,
travelRollSecs,3,Legacy fixed roll interval. rollMinSecs/rollMaxSecs supersede it.,,,
travelTarget,10,Legacy fixed segment target. segBase x diltransience supersedes it.,,,
travelTapR,15,"FLOOR for how near a tap must land on a travel element, in art pixels. The real reach is the element's own size scaled up; this is the minimum.",,,
segBase,5,"Track Segments to bridge a link, before diltransience and world state.",,,
rollMinSecs,1,Fastest the track event roll can come round (navigation GDD 4: every 1-3s).,,,
rollMaxSecs,3,Slowest the track event roll can come round. Enemy density moves it.,,,
aggroLockSecs,5,Default countdown before an aggro enemy forces the encounter.,,,
exitKeepPct,0.6,Crystals kept when EXITING at an intermediate platform.,,,
defeatKeepPct,0.1,Crystals kept on defeat.,,,
itemLossOnExit,0.4,Chance each unbanked item is lost when exiting early.,,,
itemLossOnDefeat,0.9,Chance each unbanked item is lost on defeat.,,,
fogPeekHide,1.6,Fog at or above this hides a station's details from the map.,,,
startLineKeys,L1|L2,Line Keys the player begins with.,,,
affinitySlots,2,How many Emotional Affinities a player picks at creation.,,,
armorSlots,1,Emotional Armor pieces worn at once.,,,
startArmor,ARM_SCARS,The armor a new profile begins in.,,,
startSets,LO_ANGER|LO_SADNESS|LO_JOY,The Move Sets a new profile begins with.,,,`,

/* --- sounds ---
   synthesised at runtime, no audio files. wave: square|sawtooth|triangle|sine|noise.  */
sounds: `id,wave,f0,f1,dur,gain,echo,description
tap,square,980,1460,80,0.46,0.3,Adding an ability to the line.
place,square,620,1760,130,0.4,0.35,The station lands on your line and flashes white.
resist,square,880,760,120,0.34,0.3,"A layer shrugs off its own emotion. Played twice, descending."
hit_anger,square,300,90,150,0.36,0.28,Anger lands: hard and low.
hit_surprise,sawtooth,1200,300,130,0.3,0.34,Surprise lands: a sharp drop.
hit_disgust,noise,420,200,180,0.3,0.3,Disgust lands: wet and dull.
hit_joy,square,900,1800,120,0.3,0.32,Joy lands: bright and rising.
hit_sadness,triangle,520,180,220,0.3,0.38,Sadness lands: a long fall.
hit_fear,noise,900,1400,120,0.26,0.4,Fear lands: a cold hiss.
buff_up,square,420,1500,260,0.28,0.35,Something is lifted.
debuff_down,sawtooth,1500,260,300,0.3,0.38,Something is dragged down.
status_on,noise,200,1100,520,0.32,0.5,A status takes hold.
sheatheE,sawtooth,1500,220,150,0.3,0.22,Enemy UI element drawn into place. Lower.
sheatheP,sawtooth,2100,340,140,0.28,0.22,Player UI element drawn into place. Higher.
slot,triangle,300,1500,150,0.3,0.45,A temporary slot flies in from the opponent.
remove,square,520,220,90,0.34,0.24,Removing a station.
depart,sawtooth,240,70,420,0.26,0.45,The line departs and charge is spent.
travel,square,150,150,38,0.1,0.15,Line scrolling to the next station.
arrive,square,880,880,45,0.14,0.3,Station reaches the head and lights up.
hit,noise,700,700,190,0.34,0.4,Off-type hit.
absorb,square,300,1200,260,0.24,0.5,Same-type hit: the layer absorbs it.
block,noise,1600,1600,90,0.3,0.35,"Shield blocks, or shield goes up."
breaklayer,sawtooth,760,80,340,0.28,0.55,A layer flashes and breaks.
regrow,triangle,120,520,300,0.16,0.4,The broken layer regrows at the back.
clash,noise,240,240,1500,0.4,0.65,Death: the chevrons meet.
speak,square,620,540,42,0.09,0.12,One letter of dialogue appearing.
win,square,440,1320,620,0.24,0.55,Victory.
lose,sawtooth,320,50,950,0.28,0.6,Defeat.
map_select,square,760,1180,70,0.3,0.25,MAP: an adjacent station is chosen.
map_depart,sawtooth,180,900,620,0.3,0.5,MAP: the wipe opens and the train pulls away.
map_clack,square,210,150,34,0.13,0.18,MAP: one rail joint passing under the train.
map_announce,triangle,520,1040,300,0.26,0.4,MAP: 'Propera parada' over the carriage speaker.
map_flash,noise,300,2600,700,0.34,0.55,"MAP: the white flood, the train leaving the frame."
map_arrive,square,660,1980,540,0.26,0.45,MAP: the station banner lands.
map_return,sawtooth,1300,260,560,0.24,0.42,MAP: the wipe closes back onto the map.
map_step,triangle,900,1350,90,0.2,0.22,MAP: the player marker moving one station.
map_pick,square,1180,1760,70,0.26,0.2,MAP: a Track Segment is grabbed.
map_collect,square,880,2200,150,0.28,0.35,MAP: it lands in the Emotional Trip bar.
map_entity,noise,520,240,180,0.28,0.45,MAP: an Emotional Entity is prodded.
ui_tap,square,900,1240,52,0.22,0.14,MAP: a button.
ui_open,square,520,1180,120,0.24,0.28,MAP: a panel comes up.
ui_close,square,1180,520,110,0.2,0.22,MAP: a panel goes away.
ui_page,square,760,1010,60,0.18,0.16,MAP: moving between tabs.
ui_equip,square,640,1560,170,0.26,0.32,MAP: something is put on.
ui_deny,sawtooth,340,180,150,0.24,0.2,"MAP: refused - not owned, no route, no key."
ui_station,triangle,680,1180,140,0.24,0.34,MAP: a station panel opens.`,

/* --- units ---
   layers are outermost-first and rotate as they take hits. pool = usable abilities.  */
units: `id,name,emotion,max_ms,start_ec_pct,layers,pool,line_dir,line_cap,max_bonus_slots,loadouts,ai_profile,init,start_shield,max_layers_override,tags,enabled,notes
player,You,,400,0.4,JOY|SADNESS,ATK_ANGER|ATK_SADNESS|ATK_JOY|DEFEND|RECHARGE|HVY_ANGER|HVY_SADNESS|HVY_JOY|GEN_DISGUST|GEN_ANGER|ROT|INFLICT_SAD,1,3,6,LO_ANGER|LO_SADNESS|LO_JOY,,10,0,,PLAYER,1,
enemy,The Commuter,ANGER,250,0.4,ANGER|ANGER|SADNESS,ATK_ANGER|ATK_SADNESS|ATK_JOY|DEFEND|RECHARGE|HVY_ANGER|HVY_SADNESS|HVY_JOY|BLIND,-1,3,6,,GREEDY_MAX_DAMAGE,8,0,,ENEMY,1,"AI reads the matchups sheet, so retuning it retunes the AI."`,

/* --- abilities ---
   kind DAMAGE|SHIELD · power = damage or shield charges · blank emotion = typeless
   (never matches a layer) · hits_layer = whether a hit rotates the target's queue.  */
abilities: `id,name,emotion,cost,kind,power,charge,hits_layer,icon,target,reach,self_ms,self_ec,ec_push_target,ec_drain_target,heal,shield_gain,pierce_shield,ignore_layer,repeat,cooldown,uses,blurb,action,emotions,crit_chance,status_apply,status_chance,status_duration,combo_tag,requires_prev_tag,synergy_group,wild_target,rarity,unlock,enabled,notes
ATK_ANGER,Heated Punch,ANGER,20,DAMAGE,35,0,1,BOLT,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,3,Attack. Cracks the outermost {LAYER}.,0,,,,0,0,,,,LOWEST_MS,COMMON,,1,
ATK_SADNESS,Cold Shoulder,SADNESS,20,DAMAGE,35,0,1,DROP,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,3,Attack. Cracks the outermost {LAYER}.,0,,,,0,0,,,,LOWEST_MS,COMMON,,1,
ATK_JOY,Manic Grin,JOY,20,DAMAGE,35,0,1,SPARK,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,3,Attack. Cracks the outermost {LAYER}.,0,,,,0,0,,,,LOWEST_MS,COMMON,,1,
DEFEND,Block,,10,SHIELD,1,0,0,SHIELD,SELF,SINGLE,0,0,0,0,0,1,0,0,1,1,3,Defence. Blocks the next hit outright.,1,,,,0,0,,,,SELF,COMMON,,1,
HVY_ANGER,Rage,ANGER,45,DAMAGE,90,2,1,BOLT,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,2,"Attack. *Charges* first, then hits for triple.",0,,,,0,0,,,,LOWEST_MS,COMMON,,1,
HVY_SADNESS,Grief,SADNESS,45,DAMAGE,90,2,1,DROP,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,2,"Attack. *Charges* first, then hits for triple.",0,,,,0,0,,,,LOWEST_MS,COMMON,,1,
HVY_JOY,Mania,JOY,60,DAMAGE,130,3,1,SPARK,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,2,"Attack. The hardest hit there is, after a long *charge*.",0,,,,0,0,,,,LOWEST_MS,COMMON,,1,
RECHARGE,Recharge,,0,CHARGE,20,0,0,CHARGE,SELF,SINGLE,5,0,0,0,0,0,0,0,1,1,3,Buff. Trades your own {MS} for {EC}.,1,,,,0,0,,,,SELF,COMMON,,1,Gains 20 EC and costs 5 of your own MS — which also lowers your ceiling.
GEN_DISGUST,Bile,DISGUST,15,ADDLAYER,1,0,0,ROT,SELF,SINGLE,0,0,0,0,0,0,0,0,1,1,2,Defence. Grows a {LAYER} that *never regrows* once broken.,0,,,,0,0,,,,SELF,COMMON,,1,Grows one extra Disgust layer. Grown layers are TEMPORARY: once broken they never regrow.
GEN_ANGER,Bristle,ANGER,15,ADDLAYER,1,0,0,ROT,SELF,SINGLE,0,0,0,0,0,0,0,0,1,1,2,Defence. Grows a {LAYER} that *never regrows* once broken.,0,,,,0,0,,,,SELF,COMMON,,1,Grows one extra Anger layer. Grown layers are TEMPORARY: once broken they never regrow.
ROT,Fester,DISGUST,25,DEBUFF,0,0,0,ROT,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,2,Debuff. Target cannot regrow *2* {LAYERS} for *2 turns*.,0,,,NO_REGEN,0,2,,,,LOWEST_MS,COMMON,,1,For 2 turns the target cannot regrow 2 of its broken layers.
INFLICT_SAD,Self-Harm,SADNESS,30,DEBUFF,0,0,0,DROP,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,2,Status. Target attacks *itself* each round for *2 turns*.,0,,,SAD,0,2,,,,LOWEST_MS,COMMON,,1,"Each round end the target turns one of its own attacks on itself. NOTE: distinct from SELF_HARM, which is the Overload-forced station."
BLIND,Blinded by Hate,ANGER,30,DEBUFF,0,0,0,EYE,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,1,2,Debuff. Target *misses half* its attacks for *2 turns*.,0,,,BLINDED,0,2,,,,LOWEST_MS,COMMON,,1,ENEMY ability. The target misses half its attacks for 2 turns.
SELF_HARM,Self Harm,,0,SELFHARM,25,0,0,WARN,SELF,SINGLE,0,0,0,0,0,0,0,0,1,0,0,Status. Forced by {OVERLOAD}; costs you {MS}.,0,,,,0,0,,,,SELF,OVERLOAD,,1,OVERLOAD ONLY. Forced into your line when Charge passes your ceiling. Cannot be moved or removed.
FEED,Feed,,0,FEED,30,0,0,DROP,ENEMY,SINGLE,0,0,0,0,0,0,0,0,1,0,0,Status. Forced by {OVERLOAD}; *heals* your opponent.,0,,,,0,0,,,,AS_WRITTEN,OVERLOAD,,1,OVERLOAD ONLY. Heals your opponent. Cannot be moved or removed.`,

/* --- loadouts ---
   one Loadout per emotion. Slots are positional and a blank slot is a real
   empty slot in the panel. A Loadout may hold any ability whose emotion set
   includes its own emotion (see abilities.emotions).  */
loadouts: `id,emotion,name,slot1,slot2,slot3,slot4,tier,ec_mod,passive,cost,trade_in,enabled,notes
LO_ANGER,ANGER,Anger,ATK_ANGER,HVY_ANGER,GEN_ANGER,,1,0,,,,1,
LO_SADNESS,SADNESS,Sadness,ATK_SADNESS,HVY_SADNESS,INFLICT_SAD,,1,0,,,,1,
LO_JOY,JOY,Joy,ATK_JOY,HVY_JOY,,,1,0,,,,1,
LO_DISGUST,DISGUST,Disgust,GEN_DISGUST,ROT,,,1,0,,,,1,
LO_SURPRISE,SURPRISE,Surprise,,,,,1,0,,,,1,No Surprise abilities exist yet.
LO_FEAR,FEAR,Fear,,,,,1,0,,,,1,No Fear abilities exist yet.`,

/* --- stations ---
   one row per PLACE, not per stop: an interchange is a single station that
   several lines call at. `lines` and `emotions` are that station's own — seeded
   from the lines calling there, but free to diverge. `state` is the station's
   condition and drives what the map shows and what it does to a player passing
   through; blank means nothing special. x/y are schematic world units — the
   renderer squares every link to 45 degrees, so they need only be roughly right.  */
stations: `id,name,lines,emotions,state,spawn,fog,threat,diltransience,x,y,enabled,notes
TRINITAT_NOVA,Trinitat Nova,L3|L4,DISGUST|JOY,,,,,,414,24,1,
ROQUETES,Roquetes,L3,DISGUST,,,,,,396,42,1,
CANYELLES,Canyelles,L3,DISGUST,,,,,,378,60,1,
VIA_JULIA,Via Júlia,L4,JOY,,,,,,432,60,1,
VALLDAURA,Valldaura,L3,DISGUST,,,,,,360,78,1,
MUNDET,Mundet,L3,DISGUST,,,,,,342,96,1,
MONTBAU,Montbau,L3,DISGUST,,,,,,324,114,1,
LLUCMAJOR,Llucmajor,L4,JOY,,,,,,432,120,1,
EL_COLL_LA_TEIXONERA,El Coll | La Teixonera,L5,SADNESS,,,,,,342,126,1,
EL_CARMEL,El Carmel,L5,SADNESS,,,,,,360,126,1,
HORTA,Horta,L5,SADNESS,,,,,,378,126,1,
FONDO,Fondo,L1,ANGER,,,,,,540,126,1,
SARRIA,Sarrià,L6,FEAR,,,,,,186,144,1,
VALL_D_HEBRON,Vall d'Hebron,L3|L5,DISGUST|SADNESS,,,,,,324,144,1,
VILAPICINA,Vilapicina,L5,SADNESS,,,,,,396,144,1,
SANTA_COLOMA,Santa Coloma,L1,ANGER,,,,,,522,144,1,
LES_TRES_TORRES,Les Tres Torres,L6,FEAR,,,,,,204,162,1,
PENITENTS,Penitents,L3,DISGUST,,,,,,306,162,1,
VIRREI_AMAT,Virrei Amat,L5,SADNESS,,,,,,414,162,1,
BARO_DE_VIVER,Baró de Viver,L1,ANGER,,,,,,504,162,1,
LA_BONANOVA,La Bonanova,L6,FEAR,,,,,,222,180,1,
VALLCARCA,Vallcarca,L3,DISGUST,,,,,,306,180,1,
MARAGALL,Maragall,L4|L5,JOY|SADNESS,,,,,,432,180,1,
TRINITAT_VELLA,Trinitat Vella,L1,ANGER,,,,,,486,180,1,
MUNTANER,Muntaner,L6,FEAR,,,,,,240,198,1,
LESSEPS,Lesseps,L3,DISGUST,,,,,,306,198,1,
GUINARDO_HOSPITAL_DE_SANT_PAU,Guinardó | Hospital de Sant Pau,L4,JOY,,,,,,414,198,1,
TORRAS_I_BAGES,Torras i Bages,L1,ANGER,,,,,,468,198,1,
CONGRES,Congrés,L5,SADNESS,,,,,,432,210,1,
SANT_GERVASI,Sant Gervasi,L6,FEAR,,,,,,258,216,1,
FONTANA,Fontana,L3,DISGUST,,,,,,306,216,1,
ALFONS_X,Alfons X,L4,JOY,,,,,,396,216,1,
SANT_ANDREU,Sant Andreu,L1,ANGER,,,,,,450,216,1,
ZONA_UNIVERSITARIA,Zona Universitària,L3,DISGUST,,,,,,72,234,1,
PALAU_REIAL,Palau Reial,L3,DISGUST,,,,,,90,234,1,
MARIA_CRISTINA,Maria Cristina,L3,DISGUST,,,,,,108,234,1,
GRACIA,Gràcia,L6,FEAR,,,,,,276,234,1,
DIAGONAL,Diagonal,L3|L5,DISGUST|SADNESS,,,,,,306,234,1,
JOANIC,Joanic,L4,JOY,,,,,,378,234,1,
FABRA_I_PUIG,Fabra i Puig,L1,ANGER,,,,,,432,234,1,
LES_CORTS,Les Corts,L3,DISGUST,,,,,,126,252,1,
PLACA_DEL_CENTRE,Plaça del Centre,L3,DISGUST,,,,,,144,252,1,
ENTENCA,Entença,L5,SADNESS,,,,,,216,252,1,
HOSPITAL_CLINIC,Hospital Clínic,L5,SADNESS,,,,,,252,252,1,
PROVENCA,Provença,L6,FEAR,,,,,,288,252,1,
GIRONA,Girona,L4,JOY,,,,,,330,252,1,
VERDAGUER,Verdaguer,L4|L5,JOY|SADNESS,,,,,,360,252,1,
SANT_PAU_DOS_DE_MAIG,Sant Pau | Dos de Maig,L5,SADNESS,,,,,,378,252,1,
CAMP_DE_L_ARPA,Camp de l'Arpa,L5,SADNESS,,,,,,396,252,1,
LA_SAGRERA,La Sagrera,L1|L5,ANGER|SADNESS,,,,,,414,252,1,
SANTS_ESTACIO,Sants Estació,L3|L5,DISGUST|SADNESS,,,,,,180,270,1,
PASSEIG_DE_GRACIA,Passeig de Gràcia,L2|L3|L4,SURPRISE|DISGUST|JOY,,,,,,306,270,1,
TETUAN,Tetuan,L2,SURPRISE,,,,,,324,270,1,
MONUMENTAL,Monumental,L2,SURPRISE,,,,,,342,270,1,
SAGRADA_FAMILIA,Sagrada Família,L2|L5,SURPRISE|SADNESS,,,,,,360,270,1,
ENCANTS,Encants,L2,SURPRISE,,,,,,378,270,1,
NAVAS,Navas,L1,ANGER,,,,,,396,270,1,
CORNELLA_CENTRE,Cornellà Centre,L5,SADNESS,,,,,,18,288,1,
GAVARRA,Gavarra,L5,SADNESS,,,,,,36,288,1,
SANT_ILDEFONS,Sant Ildefons,L5,SADNESS,,,,,,54,288,1,
CAN_BOIXERES,Can Boixeres,L5,SADNESS,,,,,,72,288,1,
CAN_VIDALET,Can Vidalet,L5,SADNESS,,,,,,90,288,1,
PUBILLA_CASES,Pubilla Cases,L5,SADNESS,,,,,,108,288,1,
COLLBLANC,Collblanc,L5,SADNESS,,,,,,126,288,1,
BADAL,Badal,L5,SADNESS,,,,,,162,288,1,
PLACA_DE_SANTS,Plaça de Sants,L1|L5,ANGER|SADNESS,,,,,,180,288,1,
HOSTAFRANCS,Hostafrancs,L1,ANGER,,,,,,198,288,1,
ESPANYA,Espanya,L1|L3,ANGER|DISGUST,,,,,,216,288,1,
ROCAFORT,Rocafort,L1,ANGER,,,,,,234,288,1,
URGELL,Urgell,L1,ANGER,,,,,,252,288,1,
UNIVERSITAT,Universitat,L1|L2,ANGER|SURPRISE,,,,,,270,288,1,
CATALUNYA,Catalunya,L1|L3|L6,ANGER|DISGUST|FEAR,,,,,,288,288,1,
URQUINAONA,Urquinaona,L1|L4,ANGER|JOY,,,,,,306,288,1,
ARC_DE_TRIOMF,Arc de Triomf,L1,ANGER,,,,,,324,288,1,
MARINA,Marina,L1,ANGER,,,,,,342,288,1,
GLORIES,Glòries,L1,ANGER,,,,,,360,288,1,
CLOT,Clot,L1|L2,ANGER|SURPRISE,,,,,,378,288,1,
BAC_DE_RODA,Bac de Roda,L2,SURPRISE,,,,,,396,288,1,
SANT_MARTI,Sant Martí,L2,SURPRISE,,,,,,414,288,1,
LA_PAU,La Pau,L2|L4,SURPRISE|JOY,,,,,,432,288,1,
VERNEDA,Verneda,L2,SURPRISE,,,,,,450,288,1,
ARTIGUES_SANT_ADRIA,Artigues | Sant Adrià,L2,SURPRISE,,,,,,468,288,1,
SANT_ROC,Sant Roc,L2,SURPRISE,,,,,,486,288,1,
GORG,Gorg,L2,SURPRISE,,,,,,504,288,1,
PEP_VENTURA,Pep Ventura,L2,SURPRISE,,,,,,522,288,1,
BADALONA_POMPEU_FABRA,Badalona Pompeu Fabra,L2,SURPRISE,,,,,,540,288,1,
MERCAT_NOU,Mercat Nou,L1,ANGER,,,,,,162,306,1,
BESOS,Besòs,L4,JOY,,,,,,450,306,1,
POBLE_SEC,Poble Sec,L3,DISGUST,,,,,,216,312,1,
SANT_ANTONI,Sant Antoni,L2,SURPRISE,,,,,,252,312,1,
LICEU,Liceu,L3,DISGUST,,,,,,288,312,1,
JAUME_I,Jaume I,L4,JOY,,,,,,306,312,1,
SANTA_EULALIA,Santa Eulàlia,L1,ANGER,,,,,,144,324,1,
PARAL_LEL,Paral·lel,L2|L3,SURPRISE|DISGUST,,,,,,234,330,1,
DRASSANES,Drassanes,L3,DISGUST,,,,,,270,330,1,
BARCELONETA,Barceloneta,L4,JOY,,,,,,324,330,1,
CIUTADELLA_VILA_OLIMPICA,Ciutadella | Vila Olímpica,L4,JOY,,,,,,342,330,1,
BOGATELL,Bogatell,L4,JOY,,,,,,360,330,1,
LLACUNA,Llacuna,L4,JOY,,,,,,378,330,1,
POBLENOU,Poblenou,L4,JOY,,,,,,396,330,1,
SELVA_DE_MAR,Selva de Mar,L4,JOY,,,,,,414,330,1,
EL_MARESME_FORUM,El Maresme | Fòrum,L4,JOY,,,,,,432,330,1,
BESOS_MAR,Besòs Mar,L4,JOY,,,,,,450,330,1,
HOSPITAL_DE_BELLVITGE,Hospital de Bellvitge,L1,ANGER,,,,,,18,342,1,
BELLVITGE,Bellvitge,L1,ANGER,,,,,,36,342,1,
L_HOSPITALET_AV_CARRILET,L'Hospitalet | Av. Carrilet,L1,ANGER,,,,,,54,342,1,
RAMBLA_JUST_OLIVERAS,Rambla Just Oliveras,L1,ANGER,,,,,,72,342,1,
CAN_SERRA,Can Serra,L1,ANGER,,,,,,90,342,1,
FLORIDA,Florida,L1,ANGER,,,,,,108,342,1,
TORRASSA,Torrassa,L1,ANGER,,,,,,126,342,1,`,

/* --- metro_lines ---
   one row per line, `stations` in running order. Colour is not stored: it
   comes from the emotion, so the map cannot drift out of step with battle.  */
metro_lines: `id,name,emotion,stations,enabled,notes
L1,Línia 1,ANGER,HOSPITAL_DE_BELLVITGE|BELLVITGE|L_HOSPITALET_AV_CARRILET|RAMBLA_JUST_OLIVERAS|CAN_SERRA|FLORIDA|TORRASSA|SANTA_EULALIA|MERCAT_NOU|PLACA_DE_SANTS|HOSTAFRANCS|ESPANYA|ROCAFORT|URGELL|UNIVERSITAT|CATALUNYA|URQUINAONA|ARC_DE_TRIOMF|MARINA|GLORIES|CLOT|NAVAS|LA_SAGRERA|FABRA_I_PUIG|SANT_ANDREU|TORRAS_I_BAGES|TRINITAT_VELLA|BARO_DE_VIVER|SANTA_COLOMA|FONDO,1,
L2,Línia 2,SURPRISE,PARAL_LEL|SANT_ANTONI|UNIVERSITAT|PASSEIG_DE_GRACIA|TETUAN|MONUMENTAL|SAGRADA_FAMILIA|ENCANTS|CLOT|BAC_DE_RODA|SANT_MARTI|LA_PAU|VERNEDA|ARTIGUES_SANT_ADRIA|SANT_ROC|GORG|PEP_VENTURA|BADALONA_POMPEU_FABRA,1,
L3,Línia 3,DISGUST,ZONA_UNIVERSITARIA|PALAU_REIAL|MARIA_CRISTINA|LES_CORTS|PLACA_DEL_CENTRE|SANTS_ESTACIO|ESPANYA|POBLE_SEC|PARAL_LEL|DRASSANES|LICEU|CATALUNYA|PASSEIG_DE_GRACIA|DIAGONAL|FONTANA|LESSEPS|VALLCARCA|PENITENTS|VALL_D_HEBRON|MONTBAU|MUNDET|VALLDAURA|CANYELLES|ROQUETES|TRINITAT_NOVA,1,
L4,Línia 4,JOY,TRINITAT_NOVA|VIA_JULIA|LLUCMAJOR|MARAGALL|GUINARDO_HOSPITAL_DE_SANT_PAU|ALFONS_X|JOANIC|VERDAGUER|GIRONA|PASSEIG_DE_GRACIA|URQUINAONA|JAUME_I|BARCELONETA|CIUTADELLA_VILA_OLIMPICA|BOGATELL|LLACUNA|POBLENOU|SELVA_DE_MAR|EL_MARESME_FORUM|BESOS_MAR|BESOS|LA_PAU,1,
L5,Línia 5,SADNESS,CORNELLA_CENTRE|GAVARRA|SANT_ILDEFONS|CAN_BOIXERES|CAN_VIDALET|PUBILLA_CASES|COLLBLANC|BADAL|PLACA_DE_SANTS|SANTS_ESTACIO|ENTENCA|HOSPITAL_CLINIC|DIAGONAL|VERDAGUER|SAGRADA_FAMILIA|SANT_PAU_DOS_DE_MAIG|CAMP_DE_L_ARPA|LA_SAGRERA|CONGRES|MARAGALL|VIRREI_AMAT|VILAPICINA|HORTA|EL_CARMEL|EL_COLL_LA_TEIXONERA|VALL_D_HEBRON,1,
L6,Línia 6,FEAR,CATALUNYA|PROVENCA|GRACIA|SANT_GERVASI|MUNTANER|LA_BONANOVA|LES_TRES_TORRES|SARRIA,1,`,

/* --- travel_elements ---
   what can appear around the train during a ride. `chance` is rolled
   per element every `travelRollSecs`; `max_on_screen` caps how many may exist at once
   and `max_per_trip` how many one ride may ever produce. life_min/life_max are seconds.
   `drift` is how fast it moves relative to the track — above 1 reads as nearer the
   camera. Every one of these is a BASE, scaled by the target station's `spawn` column
   and by any temporary modifier in play.  */
travel_elements: `id,name,kind,motion,chance,max_on_screen,max_per_trip,life_min,life_max,size,drift,worth,payload,amount,lock_secs,enabled,notes
TRACK_SEGMENT,Track Segment,SEGMENT,FLYBY,0.25,8,0,6,9,11,1.15,1,NONE,0,0,1,"Bridges the link. 0 in max_per_trip means UNLIMITED. Its life is longer than a crossing on purpose: a segment must stay tappable until it leaves the bottom, never fade out mid-screen."
CRYSTAL_SHARD,Crystal Shard,CRYSTAL,FLYBY,0.09,2,0,6,9,12,1.0,0,CRYSTAL,1,0,1,A rotating prism in the line's own colour. Rare on purpose.
SETTLED_ECHO,Settled Echo,LOOT,PARALLEL,0.12,3,12,4.0,8.0,10,0.15,0,ITEM,1,0,1,Holds station alongside the train for a while. Rolls an item.
EMOTIONAL_ENTITY,Emotional Entity,ENEMY_PASSIVE,PARALLEL,0.1,2,4,5.0,15.0,13,0.45,0,NONE,0,0,1,Floats past. Tap to pick the fight; ignore it and it leaves.
HUNTER,Hunter,ENEMY_AGGRO,PARALLEL,0.05,1,2,8.0,14.0,14,0.3,0,NONE,0,5,1,Locks on. When the countdown runs out it forces the encounter.`,

/* --- items ---
   PLACEHOLDERS. Item design is not written yet; these exist so the roll-and-lose
   machinery has something to roll. `weight` is relative drop likelihood.  */
items: `id,name,emotion,weight,cost,enabled,notes
TOKEN_RUST,Rusted Token,ANGER,30,,1,PLACEHOLDER — item design is not written yet.
TICKET_TORN,Torn Ticket,SADNESS,30,,1,PLACEHOLDER
CHARM_BENT,Bent Charm,JOY,20,,1,PLACEHOLDER
LENS_CRACKED,Cracked Lens,FEAR,12,,1,PLACEHOLDER
KEYRING_LOST,Lost Keyring,SURPRISE,8,,1,PLACEHOLDER`,

/* --- armor ---
   Emotional Armor (progression GDD 3). `ms_mod` is added to the player's base
   MaxMS; layer1/layer2 are the Emotional Layers it grants in battle — blank means the
   armor grants none. One `passive` per piece, resolved by ArmorFx in MAP/src/gear.js.
   `cost` and `trade_in` are for the store, which does not exist yet.  */
armor: `id,name,tier,ms_mod,layer1,layer2,passive,cost,trade_in,enabled,notes
ARM_SCARS,Calloused Scars,1,80,ANGER,,PAS_THICKSKIN,,,1,"Starter. One layer, and it is the one that hits back."
ARM_SHELL,Apathetic Shell,2,120,DISGUST,FEAR,PAS_NUMB,120 DISGUST + 60 FEAR,ARM_SCARS,1,"Two layers. Slow to feel anything, which is the point."
ARM_GLASSES,Rose-Tinted Glasses,2,60,JOY,SURPRISE,PAS_DENIAL,140 JOY + 40 SURPRISE,ARM_SCARS,1,"Least stamina, brightest layers."
ARM_SHOULDERS,Heavy Shoulders,3,150,SADNESS,ANGER,PAS_ENDURE,220 SADNESS + 90 ANGER,ARM_SHELL,1,Carries the most and moves the slowest.`,

/* --- world_bands ---
   day / hour / weather -> multipliers on a station's live attributes. Every
   MATCHING row multiplies, so BASE is the floor and the rest stack on it. Hours are
   BARCELONA local and to_hour is exclusive; a band may wrap past midnight. `weather`
   comes from WorldState (stubbed today, a real API later). Higher priority wins nothing
   on its own — it only orders the rows for readability.  */
world_bands: `id,day,from_hour,to_hour,weather,fog,density,aggro,diltransience,priority,enabled,notes
BASE,*,0,24,*,1,1,1,1,0,1,The floor everything else multiplies onto.
NIGHT,*,23,5,*,1.8,1.35,1.4,1.15,2,1,"Late trains. Thicker, meaner, longer."
DAWN,*,5,8,*,1.3,0.8,0.7,0.95,2,1,"Thin crowds, low threat."
RUSH_AM,MON|TUE|WED|THU|FRI,8,10,*,0.8,1.25,1.1,0.9,3,1,Packed and quick.
RUSH_PM,MON|TUE|WED|THU|FRI,18,21,*,0.9,1.3,1.2,0.9,3,1,Packed and fraying.
WEEKEND,SAT|SUN,0,24,*,1.1,0.9,0.85,1.1,1,1,"Slower, stranger."
RAIN,*,0,24,RAIN,1.6,1.1,1.05,1.2,4,1,Wet track. Poor visibility.
STORM,*,0,24,STORM,2.2,1.4,1.5,1.35,5,1,Everything is worse.
CLEAR,*,0,24,CLEAR,0.85,1,1,0.95,4,1,You can see what is coming.`
};

/* --- CSV reader: handles quoted fields, so notes may contain commas ---- */
function splitCSVLine(line){
  const out=[]; let cur="", q=false;
  for(let i=0;i<line.length;i++){
    const c=line[i];
    if(q){
      if(c==='"'){ if(line[i+1]==='"'){cur+='"'; i++;} else q=false; }
      else cur+=c;
    }else{
      if(c==='"') q=true;
      else if(c===",") { out.push(cur); cur=""; }
      else cur+=c;
    }
  }
  out.push(cur); return out;
}
function parseCSV(src){
  const lines = src.trim().split(/\r?\n/).filter(l=>l.trim()!=="");
  const head = splitCSVLine(lines.shift()).map(h=>h.trim());
  return lines.map(line=>{
    const cells = splitCSVLine(line);
    const row = {};
    head.forEach((h,i)=>{
      let v = (cells[i]??"").trim();
      if(SCHEMA.list.includes(h))      row[h] = v ? v.split("|").map(s=>s.trim()) : [];
      else if(SCHEMA.bool.includes(h)) row[h] = v==="1"||v.toUpperCase()==="TRUE";
      else if(v!=="" && !isNaN(Number(v))) row[h] = Number(v);
      else row[h] = v;
    });
    return row;
  });
}
const byId = rows => Object.fromEntries(rows.map(r=>[r.id,r]));

const EMOTIONS  = byId(parseCSV(DATA.emotions));
const ABILITIES = byId(parseCSV(DATA.abilities));
const UNITS     = byId(parseCSV(DATA.units));
const RULES     = Object.fromEntries(parseCSV(DATA.rules).map(r=>[r.key,r.value]));
const SOUNDS    = byId(parseCSV(DATA.sounds));
const LOADOUTS  = byId(parseCSV(DATA.loadouts).filter(r=>r.enabled));
const STATIONS  = byId(parseCSV(DATA.stations).filter(r=>r.enabled));
const LINES     = parseCSV(DATA.metro_lines).filter(r=>r.enabled);
const ELEMENTS  = byId(parseCSV(DATA.travel_elements).filter(r=>r.enabled));
const ITEMS     = byId(parseCSV(DATA.items).filter(r=>r.enabled));
const ARMOR     = byId(parseCSV(DATA.armor).filter(r=>r.enabled));
const WORLD_BANDS = parseCSV(DATA.world_bands).filter(r=>r.enabled);
